/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantAdmin } from '../../models/tenant-admin';

export interface GetTenantAdminById$Params {

/**
 * ID del TenantAdmin a recuperar
 */
  id: number;
}

export function getTenantAdminById(http: HttpClient, rootUrl: string, params: GetTenantAdminById$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
  const rb = new RequestBuilder(rootUrl, getTenantAdminById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantAdmin>;
    })
  );
}

getTenantAdminById.PATH = '/super-admin/tenant-admins/{id}';
