/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantAdmin } from '../../models/tenant-admin';

export interface GetAllTenantAdmins$Params {
}

export function getAllTenantAdmins(http: HttpClient, rootUrl: string, params?: GetAllTenantAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TenantAdmin>>> {
  const rb = new RequestBuilder(rootUrl, getAllTenantAdmins.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TenantAdmin>>;
    })
  );
}

getAllTenantAdmins.PATH = '/super-admin/tenant-admins/all';
