/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantAdmin } from '../../models/tenant-admin';

export interface UpdateTenantAdmin$Params {

/**
 * ID del TenantAdmin a actualizar.
 */
  id: number;
      body: TenantAdmin
}

export function updateTenantAdmin(http: HttpClient, rootUrl: string, params: UpdateTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
  const rb = new RequestBuilder(rootUrl, updateTenantAdmin.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantAdmin>;
    })
  );
}

updateTenantAdmin.PATH = '/super-admin/tenant-admins/{id}';
