/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserTenantRole } from '../../models/user-tenant-role';

export interface CreateUserTenantRole$Params {
      body: UserTenantRole
}

export function createUserTenantRole(http: HttpClient, rootUrl: string, params: CreateUserTenantRole$Params, context?: HttpContext): Observable<StrictHttpResponse<UserTenantRole>> {
  const rb = new RequestBuilder(rootUrl, createUserTenantRole.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserTenantRole>;
    })
  );
}

createUserTenantRole.PATH = '/user-tenant-roles';
