/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserTenantRole } from '../../models/user-tenant-role';

export interface GetUserTenantRoleById$Params {

/**
 * ID del UserTenantRole a recuperar
 */
  id: number;
}

export function getUserTenantRoleById(http: HttpClient, rootUrl: string, params: GetUserTenantRoleById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserTenantRole>> {
  const rb = new RequestBuilder(rootUrl, getUserTenantRoleById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserTenantRole>;
    })
  );
}

getUserTenantRoleById.PATH = '/user-tenant-roles/{id}';
