/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserTenantRole } from '../../models/user-tenant-role';

export interface GetAllUserTenantRoles$Params {
}

export function getAllUserTenantRoles(http: HttpClient, rootUrl: string, params?: GetAllUserTenantRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserTenantRole>>> {
  const rb = new RequestBuilder(rootUrl, getAllUserTenantRoles.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserTenantRole>>;
    })
  );
}

getAllUserTenantRoles.PATH = '/user-tenant-roles/all';
