/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdentificationType } from '../../models/identification-type';

export interface GetById5$Params {
  id: number;
}

export function getById5(http: HttpClient, rootUrl: string, params: GetById5$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentificationType>> {
  const rb = new RequestBuilder(rootUrl, getById5.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdentificationType>;
    })
  );
}

getById5.PATH = '/mdm/identification-type/{id}';
