/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthcareProvider } from '../../models/healthcare-provider';

export interface CreateProvider$Params {
      body: HealthcareProvider
}

export function createProvider(http: HttpClient, rootUrl: string, params: CreateProvider$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthcareProvider>> {
  const rb = new RequestBuilder(rootUrl, createProvider.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthcareProvider>;
    })
  );
}

createProvider.PATH = '/mdm/healthcare-provider';
