/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthcareProvider } from '../../models/healthcare-provider';

export interface GetAllProviders$Params {
}

export function getAllProviders(http: HttpClient, rootUrl: string, params?: GetAllProviders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HealthcareProvider>>> {
  const rb = new RequestBuilder(rootUrl, getAllProviders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HealthcareProvider>>;
    })
  );
}

getAllProviders.PATH = '/mdm/healthcare-provider/all';
