/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDtoHealthcareProvider } from '../../models/page-response-dto-healthcare-provider';

export interface GetPaginatedProviders$Params {

/**
 * Índice de la página a recuperar.
 */
  pageIndex: number;

/**
 * Tamaño de la página.
 */
  pageSize: number;
}

export function getPaginatedProviders(http: HttpClient, rootUrl: string, params: GetPaginatedProviders$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoHealthcareProvider>> {
  const rb = new RequestBuilder(rootUrl, getPaginatedProviders.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoHealthcareProvider>;
    })
  );
}

getPaginatedProviders.PATH = '/mdm/healthcare-provider';
