/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Avatar } from '../../models/avatar';

export interface CreateAvatar$Params {
      body: Avatar
}

export function createAvatar(http: HttpClient, rootUrl: string, params: CreateAvatar$Params, context?: HttpContext): Observable<StrictHttpResponse<Avatar>> {
  const rb = new RequestBuilder(rootUrl, createAvatar.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Avatar>;
    })
  );
}

createAvatar.PATH = '/avatars';
