/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvatarSearchDto } from '../../models/avatar-search-dto';
import { PageResponseDtoAvatar } from '../../models/page-response-dto-avatar';

export interface GetPaginatedAvatars$Params {
  searchDto: AvatarSearchDto;

/**
 * Índice de página
 */
  pageIndex?: number;

/**
 * Tamaño de página
 */
  pageSize?: number;
}

export function getPaginatedAvatars(http: HttpClient, rootUrl: string, params: GetPaginatedAvatars$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoAvatar>> {
  const rb = new RequestBuilder(rootUrl, getPaginatedAvatars.PATH, 'get');
  if (params) {
    rb.query('searchDto', params.searchDto, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoAvatar>;
    })
  );
}

getPaginatedAvatars.PATH = '/avatars';
