/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageTenantResponse } from '../../models/page-tenant-response';

export interface ListTenants$Params {
  pageable: Pageable;
}

export function listTenants(http: HttpClient, rootUrl: string, params: ListTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<PageTenantResponse>> {
  const rb = new RequestBuilder(rootUrl, listTenants.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageTenantResponse>;
    })
  );
}

listTenants.PATH = '/super-admin/tenants';
