/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Icd10 } from '../../models/icd-10';

export interface GetAllIcd10$Params {
}

export function getAllIcd10(http: HttpClient, rootUrl: string, params?: GetAllIcd10$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Icd10>>> {
  const rb = new RequestBuilder(rootUrl, getAllIcd10.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Icd10>>;
    })
  );
}

getAllIcd10.PATH = '/mdm/diagnosis/all';
