/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Icd10 } from '../../models/icd-10';

export interface GetIcd10ById$Params {

/**
 * ID del ICD-10 Diagnosis a recuperar
 */
  id: number;
}

export function getIcd10ById(http: HttpClient, rootUrl: string, params: GetIcd10ById$Params, context?: HttpContext): Observable<StrictHttpResponse<Icd10>> {
  const rb = new RequestBuilder(rootUrl, getIcd10ById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Icd10>;
    })
  );
}

getIcd10ById.PATH = '/mdm/diagnosis/{id}';
