/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Icd10 } from '../../models/icd-10';

export interface UpdateIcd10$Params {

/**
 * ID del ICD-10 Diagnosis a actualizar.
 */
  id: number;
      body: Icd10
}

export function updateIcd10(http: HttpClient, rootUrl: string, params: UpdateIcd10$Params, context?: HttpContext): Observable<StrictHttpResponse<Icd10>> {
  const rb = new RequestBuilder(rootUrl, updateIcd10.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Icd10>;
    })
  );
}

updateIcd10.PATH = '/mdm/diagnosis/{id}';
