/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantConfig } from '../../models/tenant-config';

export interface GetMyTenantConfig$Params {
}

export function getMyTenantConfig(http: HttpClient, rootUrl: string, params?: GetMyTenantConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantConfig>> {
  const rb = new RequestBuilder(rootUrl, getMyTenantConfig.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantConfig>;
    })
  );
}

getMyTenantConfig.PATH = '/tenantConfigs/current';
