/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Municipio } from '../../models/municipio';

export interface GetAllMunicipios$Params {
}

export function getAllMunicipios(http: HttpClient, rootUrl: string, params?: GetAllMunicipios$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Municipio>>> {
  const rb = new RequestBuilder(rootUrl, getAllMunicipios.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Municipio>>;
    })
  );
}

getAllMunicipios.PATH = '/municipios/all';
