/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SuperAdmin } from '../../models/super-admin';

export interface UpdateSuperAdmin$Params {

/**
 * ID del SuperAdmin a actualizar.
 */
  id: number;
      body: SuperAdmin
}

export function updateSuperAdmin(http: HttpClient, rootUrl: string, params: UpdateSuperAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<SuperAdmin>> {
  const rb = new RequestBuilder(rootUrl, updateSuperAdmin.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SuperAdmin>;
    })
  );
}

updateSuperAdmin.PATH = '/super-admin/{id}';
