/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Provincia } from '../../models/provincia';

export interface CreateProvincia$Params {
      body: Provincia
}

export function createProvincia(http: HttpClient, rootUrl: string, params: CreateProvincia$Params, context?: HttpContext): Observable<StrictHttpResponse<Provincia>> {
  const rb = new RequestBuilder(rootUrl, createProvincia.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Provincia>;
    })
  );
}

createProvincia.PATH = '/provincias';
