/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Provincia } from '../../models/provincia';

export interface GetAllProvincias$Params {
}

export function getAllProvincias(http: HttpClient, rootUrl: string, params?: GetAllProvincias$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Provincia>>> {
  const rb = new RequestBuilder(rootUrl, getAllProvincias.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Provincia>>;
    })
  );
}

getAllProvincias.PATH = '/provincias/all';
