/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenderSearchDto } from '../../models/gender-search-dto';
import { PageResponseDtoGender } from '../../models/page-response-dto-gender';

export interface GetPaginated1$Params {
  searchDto: GenderSearchDto;
  pageIndex: number;
  pageSize: number;
}

export function getPaginated1(http: HttpClient, rootUrl: string, params: GetPaginated1$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoGender>> {
  const rb = new RequestBuilder(rootUrl, getPaginated1.PATH, 'get');
  if (params) {
    rb.query('searchDto', params.searchDto, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoGender>;
    })
  );
}

getPaginated1.PATH = '/mdm/demographic/gender';
