/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Gender } from '../../models/gender';

export interface GetAll3$Params {
}

export function getAll3(http: HttpClient, rootUrl: string, params?: GetAll3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Gender>>> {
  const rb = new RequestBuilder(rootUrl, getAll3.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Gender>>;
    })
  );
}

getAll3.PATH = '/mdm/demographic/gender/all';
