/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Allergy } from '../../models/allergy';

export interface Create6$Params {
      body: Allergy
}

export function create6(http: HttpClient, rootUrl: string, params: Create6$Params, context?: HttpContext): Observable<StrictHttpResponse<Allergy>> {
  const rb = new RequestBuilder(rootUrl, create6.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Allergy>;
    })
  );
}

create6.PATH = '/mdm/allergy';
