/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Allergy } from '../../models/allergy';

export interface GetById6$Params {
  id: number;
}

export function getById6(http: HttpClient, rootUrl: string, params: GetById6$Params, context?: HttpContext): Observable<StrictHttpResponse<Allergy>> {
  const rb = new RequestBuilder(rootUrl, getById6.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Allergy>;
    })
  );
}

getById6.PATH = '/mdm/allergy/{id}';
