/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Inject, Injectable, InjectionToken } from '@angular/core';

export const API_ROOT_URL = new InjectionToken<string>('API_ROOT_URL');

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
  // rootUrl: string = 'http://localhost:8088/api/v1';
  constructor(@Inject(API_ROOT_URL) public rootUrl: string) {} // Default root URL
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
