/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UserTenantRoleService } from './services/user-tenant-role.service';
import { ThemeControllerService } from './services/theme-controller.service';
import { TenantConfigService } from './services/tenant-config.service';
import { TenantAdminManagementService } from './services/tenant-admin-management.service';
import { SuperAdminService } from './services/super-admin.service';
import { TenantService } from './services/tenant.service';
import { TenantAdminService } from './services/tenant-admin.service';
import { ProvinciaService } from './services/provincia.service';
import { MunicipioService } from './services/municipio.service';
import { MedicalProcedureService } from './services/medical-procedure.service';
import { MedicationService } from './services/medication.service';
import { MedicalSpecialtyService } from './services/medical-specialty.service';
import { KinshipService } from './services/kinship.service';
import { HealthcareProviderService } from './services/healthcare-provider.service';
import { Icd10DiagnosisService } from './services/icd-10-diagnosis.service';
import { GenderService } from './services/gender.service';
import { CivilStatusService } from './services/civil-status.service';
import { BloodTypeService } from './services/blood-type.service';
import { DepartamentoService } from './services/departamento.service';
import { CountryService } from './services/country.service';
import { AvatarService } from './services/avatar.service';
import { AddressService } from './services/address.service';
import { VaccineService } from './services/vaccine.service';
import { IdentificationTypeService } from './services/identification-type.service';
import { AllergyService } from './services/allergy.service';
import { AuthenticationService } from './services/authentication.service';
import { AccountService } from './services/account.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UserTenantRoleService,
    ThemeControllerService,
    TenantConfigService,
    TenantAdminManagementService,
    SuperAdminService,
    TenantService,
    TenantAdminService,
    ProvinciaService,
    MunicipioService,
    MedicalProcedureService,
    MedicationService,
    MedicalSpecialtyService,
    KinshipService,
    HealthcareProviderService,
    Icd10DiagnosisService,
    GenderService,
    CivilStatusService,
    BloodTypeService,
    DepartamentoService,
    CountryService,
    AvatarService,
    AddressService,
    VaccineService,
    IdentificationTypeService,
    AllergyService,
    AuthenticationService,
    AccountService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
