/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ThemeControllerService } from './services/theme-controller.service';
import { TenantManagementControllerService } from './services/tenant-management-controller.service';
import { ProvinciaService } from './services/provincia.service';
import { MunicipioService } from './services/municipio.service';
import { DepartamentoService } from './services/departamento.service';
import { CountryService } from './services/country.service';
import { AvatarControllerService } from './services/avatar-controller.service';
import { AuthenticationService } from './services/authentication.service';
import { AccountService } from './services/account.service';
import { TenantControllerService } from './services/tenant-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ThemeControllerService,
    TenantManagementControllerService,
    ProvinciaService,
    MunicipioService,
    DepartamentoService,
    CountryService,
    AvatarControllerService,
    AuthenticationService,
    AccountService,
    TenantControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
