/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UserTenantRoleService } from './services/user-tenant-role.service';
export { ThemeControllerService } from './services/theme-controller.service';
export { TenantConfigService } from './services/tenant-config.service';
export { TenantAdminManagementService } from './services/tenant-admin-management.service';
export { SuperAdminService } from './services/super-admin.service';
export { TenantService } from './services/tenant.service';
export { TenantAdminService } from './services/tenant-admin.service';
export { ProvinciaService } from './services/provincia.service';
export { MunicipioService } from './services/municipio.service';
export { MedicalProcedureService } from './services/medical-procedure.service';
export { MedicationService } from './services/medication.service';
export { MedicalSpecialtyService } from './services/medical-specialty.service';
export { KinshipService } from './services/kinship.service';
export { HealthcareProviderService } from './services/healthcare-provider.service';
export { Icd10DiagnosisService } from './services/icd-10-diagnosis.service';
export { GenderService } from './services/gender.service';
export { CivilStatusService } from './services/civil-status.service';
export { BloodTypeService } from './services/blood-type.service';
export { DepartamentoService } from './services/departamento.service';
export { CountryService } from './services/country.service';
export { AvatarService } from './services/avatar.service';
export { AddressService } from './services/address.service';
export { VaccineService } from './services/vaccine.service';
export { IdentificationTypeService } from './services/identification-type.service';
export { AllergyService } from './services/allergy.service';
export { AuthenticationService } from './services/authentication.service';
export { AccountService } from './services/account.service';
