/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MedicalSpecialty } from '../../models/medical-specialty';

export interface GetSpecialtyById$Params {

/**
 * ID de la Medical Specialty a recuperar
 */
  id: number;
}

export function getSpecialtyById(http: HttpClient, rootUrl: string, params: GetSpecialtyById$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalSpecialty>> {
  const rb = new RequestBuilder(rootUrl, getSpecialtyById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MedicalSpecialty>;
    })
  );
}

getSpecialtyById.PATH = '/mdm/medical-specialty/{id}';
