/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MedicalProcedure } from '../../models/medical-procedure';

export interface GetProcedureById$Params {

/**
 * ID del Medical Procedure a recuperar
 */
  id: number;
}

export function getProcedureById(http: HttpClient, rootUrl: string, params: GetProcedureById$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalProcedure>> {
  const rb = new RequestBuilder(rootUrl, getProcedureById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MedicalProcedure>;
    })
  );
}

getProcedureById.PATH = '/mdm/procedure/{id}';
