/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MedicalProcedure } from '../../models/medical-procedure';

export interface UpdateProcedure$Params {

/**
 * ID del Medical Procedure a actualizar.
 */
  id: number;
      body: MedicalProcedure
}

export function updateProcedure(http: HttpClient, rootUrl: string, params: UpdateProcedure$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalProcedure>> {
  const rb = new RequestBuilder(rootUrl, updateProcedure.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MedicalProcedure>;
    })
  );
}

updateProcedure.PATH = '/mdm/procedure/{id}';
