/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDtoHospital } from '../../models/page-response-dto-hospital';

export interface GetPaginatedHospitals$Params {

/**
 * Page index to retrieve.
 */
  pageIndex?: number;

/**
 * Page size.
 */
  pageSize?: number;
}

export function getPaginatedHospitals(http: HttpClient, rootUrl: string, params?: GetPaginatedHospitals$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoHospital>> {
  const rb = new RequestBuilder(rootUrl, getPaginatedHospitals.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoHospital>;
    })
  );
}

getPaginatedHospitals.PATH = '/hospitals';
