/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Hospital } from '../../models/hospital';

export interface GetHospitalById$Params {

/**
 * ID of the Hospital to retrieve
 */
  id: number;
}

export function getHospitalById(http: HttpClient, rootUrl: string, params: GetHospitalById$Params, context?: HttpContext): Observable<StrictHttpResponse<Hospital>> {
  const rb = new RequestBuilder(rootUrl, getHospitalById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Hospital>;
    })
  );
}

getHospitalById.PATH = '/hospitals/{id}';
