/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Hospital } from '../../models/hospital';

export interface GetAllHospitals$Params {
}

export function getAllHospitals(http: HttpClient, rootUrl: string, params?: GetAllHospitals$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Hospital>>> {
  const rb = new RequestBuilder(rootUrl, getAllHospitals.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Hospital>>;
    })
  );
}

getAllHospitals.PATH = '/hospitals/all';
