/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Hospital } from '../../models/hospital';

export interface UpdateHospital$Params {

/**
 * ID of the Hospital to update.
 */
  id: number;
      body: Hospital
}

export function updateHospital(http: HttpClient, rootUrl: string, params: UpdateHospital$Params, context?: HttpContext): Observable<StrictHttpResponse<Hospital>> {
  const rb = new RequestBuilder(rootUrl, updateHospital.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Hospital>;
    })
  );
}

updateHospital.PATH = '/hospitals/{id}';
