/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDtoKinship } from '../../models/page-response-dto-kinship';

export interface GetPaginated$Params {
  pageIndex?: number;
  pageSize?: number;
}

export function getPaginated(http: HttpClient, rootUrl: string, params?: GetPaginated$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoKinship>> {
  const rb = new RequestBuilder(rootUrl, getPaginated.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoKinship>;
    })
  );
}

getPaginated.PATH = '/mdm/kinship';
