/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Medication } from '../../models/medication';

export interface UpdateMedication$Params {

/**
 * ID del Medication a actualizar.
 */
  id: number;
      body: Medication
}

export function updateMedication(http: HttpClient, rootUrl: string, params: UpdateMedication$Params, context?: HttpContext): Observable<StrictHttpResponse<Medication>> {
  const rb = new RequestBuilder(rootUrl, updateMedication.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Medication>;
    })
  );
}

updateMedication.PATH = '/mdm/medication/{id}';
