/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TokenPairDto } from '../models/token-pair-dto';
import { UserSummary } from '../models/user-summary';
export interface AuthenticationResponse {
  tokens?: TokenPairDto;
  user?: UserSummary;
}
