/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del Avatar a crear.
 */
export interface Avatar {

  /**
   * Nombre del archivo
   */
  filename?: string;

  /**
   * Identificador único
   */
  id?: number;

  /**
   * Tipo MIME del archivo
   */
  mimeType?: string;

  /**
   * Tamaño del archivo en bytes
   */
  size?: number;

  /**
   * Código del tenant
   */
  tenantCode: string;

  /**
   * ID del usuario
   */
  userId: number;
}
