/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold Avatar information
 */
export interface Avatar {

  /**
   * Contenido del avatar en bytes. Representa la imagen codificada
   */
  content?: string;

  /**
   * Nombre original del archivo subido
   */
  filename?: string;

  /**
   * Identificador único del avatar
   */
  id?: number;

  /**
   * Tipo MIME de la imagen, por ejemplo 'image/jpeg' o 'image/png'
   */
  mimeType?: string;

  /**
   * Tamaño del archivo en bytes
   */
  size?: number;

  /**
   * Code del tenant al que pertenece el usuario
   */
  tenantCode?: string;

  /**
   * Identificador del usuario al que pertenece el avatar
   */
  userId?: number;
}
