/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CivilStatusSearchDto {
  active?: boolean;
  code?: string;
  id?: number;
  name?: string;
}
