/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold Civil Status information
 */
export interface CivilStatus {
  active?: boolean;
  code: string;
  id?: number;
  name: string;
}
