/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Self-onboarding form submitted by the invited person.
 */
export interface CompleteRegistrationRequest {

  /**
   * Maternal surname.
   */
  apellidoMaterno?: string;

  /**
   * Paternal surname.
   */
  apellidoPaterno: string;

  /**
   * Definitive login email (User.email). Can be professional or personal.
   */
  loginEmail: string;

  /**
   * Legal first name.
   */
  nombre: string;

  /**
   * User-chosen password. Minimum 8 characters.
   */
  password: string;

  /**
   * Personal contact email (Person.email). Different from the login email.
   */
  personalEmail?: string;

  /**
   * Optional second given name.
   */
  segundoNombre?: string;

  /**
   * Mobile or office phone number.
   */
  telefono?: string;

  /**
   * Code of the target tenant.
   */
  tenantCode: string;

  /**
   * One-time activation token from the invitation URL.
   */
  token: string;
}
