/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del Departamento a crear.
 */
export interface Departamento {

  /**
   * Pais al que pertenece el Departamento
   */
  countryId?: number;

  /**
   * Id del Departamento
   */
  id?: number;

  /**
   * Nombre del Departamento
   */
  nombre: string;

  /**
   * Poblacion del Departamento
   */
  poblacion?: number;

  /**
   * Superficie del Departamento
   */
  superficie?: number;
}
