/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';

/**
 * Esquema que contiene la información detallada de un empleado (Médico, Administrativo, etc.)
 */
export interface Employee {

  /**
   * Objeto Direcci├│n Completo (Para creaci├│n inline)
   */
  address?: Address;

  /**
   * Apellido Materno de la Persona
   */
  apellidoMaterno?: string;

  /**
   * Apellido Paterno de la Persona
   */
  apellidoPaterno: string;

  /**
   * Cargo administrativo
   */
  cargo?: string;

  /**
   * Celular de la Persona
   */
  celular?: string;

  /**
   * Código interno del empleado
   */
  codigoEmpleado: string;

  /**
   * Tipo de Documento de Identidad
   */
  documentType?: 'DNI' | 'PASSPORT' | 'FOREIGN_ID' | 'HEALTH_CARD' | 'DRIVER_LICENSE' | 'SOCIAL_SECURITY' | 'OTHER';

  /**
   * Correo electrónico personal
   */
  email?: string;

  /**
   * Estado laboral del empleado
   */
  employeeStatus: 'ACTIVO' | 'INACTIVO' | 'SUSPENDIDO' | 'LICENCIA' | 'BAJA';

  /**
   * Tipo de empleado
   */
  employeeType: 'ADMINISTRATIVO' | 'MEDICO' | 'ENFERMERO' | 'TECNICO' | 'LABORATORISTA' | 'FARMACEUTICO' | 'OTRO';
  estadoCivil?: 'SOLTERO' | 'CASADO' | 'UNION_LIBRE' | 'SEPARADO' | 'DIVORCIADO' | 'VIUDO';

  /**
   * Fecha de ingreso al hospital
   */
  fechaIngreso?: string;

  /**
   * La fecha de nacimiento de la Persona
   */
  fechaNacimiento?: string;

  /**
   * Fecha de salida o cese
   */
  fechaSalida?: string;

  /**
   * ID del usuario asociado para login
   */
  fkIdUser?: number;
  genero?: 'MASCULINO' | 'FEMENINO' | 'OTRO' | 'DESCONOCIDO';

  /**
   * Id de la Persona
   */
  id?: number;

  /**
   * Matrícula profesional
   */
  matriculaProfesional?: string;

  /**
   * Identificador Nacional de Salud
   */
  nationalHealthId?: string;

  /**
   * Identificador Nacional
   */
  nationalId?: string;

  /**
   * Nombre de la Persona
   */
  nombre: string;

  /**
   * Número de colegiado médico
   */
  nroColegioMedico?: string;
  personTenantsIds?: Array<number>;

  /**
   * Tipo de Persona
   */
  personType?: 'DOCTOR' | 'NURSE' | 'PATIENT' | 'EMPLOYEE' | 'SUPER_ADMIN' | 'ADMIN' | 'RECEPTIONIST' | 'LAB_TECHNICIAN' | 'PHARMACIST';

  /**
   * Profesión del empleado
   */
  profesion?: string;

  /**
   * Puesto de trabajo
   */
  puesto?: string;

  /**
   * Segundo nombre de la Persona
   */
  segundoNombre?: string;

  /**
   * Telefono de la Persona
   */
  telefono: string;
}
