/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';

/**
 * Details of the Hospital to create.
 */
export interface Hospital {

  /**
   * Address of the Tenant
   */
  address?: Address;

  /**
   * Capacidad total de camas
   */
  bedCapacity?: number;

  /**
   * Code of the Tenant
   */
  code?: string;

  /**
   * Email oficial de contacto
   */
  contactEmail?: string;

  /**
   * Teléfono de contacto principal
   */
  contactPhone?: string;

  /**
   * Description of the Tenant
   */
  description?: string;

  /**
   * Disponibilidad de emergencias 24/7
   */
  emergency247?: boolean;

  /**
   * Favicon URL for branding
   */
  faviconUrl?: string;

  /**
   * Número de Fax
   */
  faxNumber?: string;

  /**
   * Categoría o nivel del hospital (e.g. Nivel III)
   */
  hospitalCategory?: string;

  /**
   * Id Tenant
   */
  id?: number;

  /**
   * Indicates if the Tenant is active
   */
  isActive?: boolean;

  /**
   * Nombre legal de la institución
   */
  legalName: string;

  /**
   * Primary Logo URL for branding
   */
  logoUrl?: string;

  /**
   * Nombre completo del Director Médico
   */
  medicalDirector?: string;

  /**
   * Matrícula profesional del Director
   */
  medicalDirectorLicense?: string;

  /**
   * Licencia sanitaria principal
   */
  medicalLicense: string;

  /**
   * Name of the Tenant
   */
  name?: string;

  /**
   * Número de quirófanos activos
   */
  operatingRoomsCount?: number;

  /**
   * URL del sello institucional oficial
   */
  sealUrl?: string;

  /**
   * Slogan o frase institucional
   */
  slogan?: string;

  /**
   * Enlaces a redes sociales (JSON)
   */
  socialLinks?: string;

  /**
   * Identificador fiscal (NIT/RUC)
   */
  taxId: string;

  /**
   * Theme ID associated with the Tenant
   */
  themeId?: number;

  /**
   * Theme Name associated with the Tenant
   */
  themeName?: string;

  /**
   * Type of the Tenant
   */
  type?: 'HOSPITAL' | 'CLINIC' | 'LABORATORY' | 'PHARMACY' | 'GLOBAL';

  /**
   * Sitio web institucional
   */
  website?: string;

  /**
   * Número oficial de WhatsApp
   */
  whatsappNumber?: string;
}
