/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold Identification Type information
 */
export interface IdentificationType {
  active?: boolean;
  code: string;
  id?: number;
  name: string;
}
