/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Invitation details provided by the TenantAdmin.
 */
export interface InvitationRequest {

  /**
   * Last name of the invitee.
   */
  apellidoPaterno: string;

  /**
   * Recipient email for the invitation link.
   */
  email: string;

  /**
   * First name of the invitee.
   */
  nombre: string;

  /**
   * Type of person being invited.
   */
  personType: 'DOCTOR' | 'NURSE' | 'PATIENT' | 'EMPLOYEE' | 'SUPER_ADMIN' | 'ADMIN' | 'RECEPTIONIST' | 'LAB_TECHNICIAN' | 'PHARMACIST';

  /**
   * Role name to assign to the user after onboarding.
   */
  roleName: string;

  /**
   * Code of the target tenant.
   */
  tenantCode: string;
}
