/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response payload carrying the result of an invitation operation.
 */
export interface InvitationResponse {

  /**
   * Invitee's paternal last name.
   */
  apellidoPaterno?: string;

  /**
   * Creation timestamp.
   */
  createdAt?: string;

  /**
   * Email that received the invitation link.
   */
  email?: string;

  /**
   * Expiration timestamp of the one-time link.
   */
  expiresAt?: string;

  /**
   * Internal ID of the invitation.
   */
  id?: number;

  /**
   * Invitee's first name.
   */
  nombre?: string;

  /**
   * Type of person being invited.
   */
  personType?: 'DOCTOR' | 'NURSE' | 'PATIENT' | 'EMPLOYEE' | 'SUPER_ADMIN' | 'ADMIN' | 'RECEPTIONIST' | 'LAB_TECHNICIAN' | 'PHARMACIST';

  /**
   * Role that will be granted upon acceptance.
   */
  roleName?: string;

  /**
   * Current status of the invitation.
   */
  status?: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'CANCELLED';

  /**
   * Code of the target tenant.
   */
  tenantCode?: string;

  /**
   * Name of the target hospital/clinic.
   */
  tenantName?: string;
}
