/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del municipio a crear.
 */
export interface Municipio {

  /**
   * Codigo del Municipio
   */
  codigoMunicipio?: number;

  /**
   * Direccion del Municipio
   */
  direccion?: string;

  /**
   * Id Municipio de un Municipio
   */
  id?: number;

  /**
   * Nombre del Municipio
   */
  nombre: string;

  /**
   * Poblacion del Municipio
   */
  poblacion?: number;

  /**
   * ID Provincia al que pertenece el Municipio
   */
  provinciaId: number;

  /**
   * Superficie del Municipio
   */
  superficie?: number;
}
