/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BloodType } from '../models/blood-type';
export interface PageResponseDtoBloodType {
  content?: Array<BloodType>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
