/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Country } from '../models/country';
export interface PageResponseDtoCountry {
  content?: Array<Country>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
