/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Municipio } from '../models/municipio';
export interface PageResponseDtoMunicipio {
  content?: Array<Municipio>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
