/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MedicalSpecialty } from '../models/medical-specialty';
export interface PageResponseDtoMedicalSpecialty {
  content?: Array<MedicalSpecialty>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
