/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Avatar } from '../models/avatar';
export interface PageResponseDtoAvatar {
  content?: Array<Avatar>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
