/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del Provincia a crear.
 */
export interface Provincia {

  /**
   * ID Departamento al que pertenece la Provincia
   */
  departamentoId: number;

  /**
   * ID de una Provincia
   */
  id?: number;

  /**
   * Nombre del Provincia
   */
  nombre: string;

  /**
   * Poblacion de la Provincia
   */
  poblacion?: number;

  /**
   * Superficie de la Provincia
   */
  superficie?: number;
}
