/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold Role information
 */
export interface Role {

  /**
   * Role description
   */
  description?: string;

  /**
   * Unique identifier of the room
   */
  id?: number;

  /**
   * Role name
   */
  name?: string;
}
