/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';

/**
 * Detalles del Tenant a crear.
 */
export interface Tenant {

  /**
   * Address of the Tenant
   */
  address?: Address;

  /**
   * Code of the Tenant
   */
  code?: string;

  /**
   * Description of the Tenant
   */
  description?: string;

  /**
   * Id Tenant
   */
  id?: number;

  /**
   * Indicates if the Tenant is active
   */
  isActive?: boolean;

  /**
   * Name of the Tenant
   */
  name?: string;

  /**
   * Theme ID associated with the Tenant
   */
  themeId?: number;

  /**
   * Type of the Tenant
   */
  type?: 'HOSPITAL' | 'CLINIC' | 'LABORATORY' | 'PHARMACY' | 'GLOBAL';
}
