/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para crear un Tenant y su TenantAdmin inicial
 */
export interface TenantCreateRequest {
  adminEmail: string;
  adminFirstName: string;
  adminLastName: string;
  adminPassword?: string;
  adminPersonType?: string;
  allowLocal?: boolean;
  code: string;
  defaultDomain?: string;
  description?: string;
  fallbackHeader?: string;
  name: string;
  type: 'HOSPITAL' | 'CLINIC' | 'LABORATORY' | 'PHARMACY' | 'GLOBAL';
}
