/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantResponse {
  allowLocal?: boolean;
  code?: string;
  createdAt?: string;
  defaultDomain?: string;
  description?: string;
  fallbackHeader?: string;
  isActive?: boolean;
  name?: string;
  tenantId?: number;
  type?: 'HOSPITAL' | 'CLINIC' | 'LABORATORY' | 'PHARMACY' | 'GLOBAL';
}
