/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Theme } from '../models/theme';
export interface Tenant {
  code: string;
  createdBy?: string;
  createdDate?: string;
  description?: string;
  id?: number;
  isActive?: boolean;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  name: string;
  theme?: Theme;
  type?: 'HOSPITAL' | 'CLINIC' | 'LABORATORY' | 'PHARMACY' | 'GLOBAL';
}
