/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del TenantConfig a crear.
 */
export interface TenantConfig {

  /**
   * Allow local logins
   */
  allowLocal?: boolean;

  /**
   * Default domain for the tenant
   */
  defaultDomain?: string;

  /**
   * Extra configuration in JSON format for future use
   */
  extraJson?: string;

  /**
   * Header to be used for tenant identification
   */
  fallbackHeader?: string;

  /**
   * Id TenantConfig
   */
  id?: number;

  /**
   * Locale setting for the tenant
   */
  locale?: string;

  /**
   * Maximum number of users allowed for the tenant
   */
  maxUsers?: number;

  /**
   * Password policy in JSON format for extensibility
   */
  passwordPolicyJson?: string;

  /**
   * Require email verification for new users
   */
  requireEmailVerification?: boolean;

  /**
   * Storage quota in bytes for the tenant
   */
  storageQuotaBytes?: number;

  /**
   * Tenant ID associated with the TenantConfig
   */
  tenantId?: number;

  /**
   * Timezone setting for the tenant
   */
  timezone?: string;
}
