/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ThemeDto {
  accentColor?: string;
  backgroundColor?: string;
  buttonTextColor?: string;
  faviconUrl?: string;
  fontFamily?: string;
  id?: number;
  linkColor?: string;
  logoUrl?: string;
  name?: string;
  primaryColor?: string;
  propertiesJson?: string;
  secondaryColor?: string;
  textColor?: string;
  themeMode?: 'LIGHT' | 'DARK' | 'AUTO';
  warnColor?: string;
}
