/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Theme {
  accentColor?: string;
  backgroundColor?: string;
  buttonTextColor?: string;
  createdBy?: string;
  createdDate?: string;
  customCss?: string;
  faviconUrl?: string;
  fontFamily?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  linkColor?: string;
  logoUrl?: string;
  name?: string;
  primaryColor?: string;
  propertiesJson?: string;
  secondaryColor?: string;
  textColor?: string;
  themeMode?: 'LIGHT' | 'DARK' | 'AUTO';
  warnColor?: string;
}
