/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
import { UserDto } from '../models/user-dto';

/**
 * Detalles del UserTenantRole a crear.
 */
export interface UserTenantRole {

  /**
   * Estado del rol (activo/inactivo)
   */
  active?: boolean;

  /**
   * Fecha en que se asignó el rol
   */
  assignedAt?: string;

  /**
   * Identificador unico
   */
  id?: number;

  /**
   * Fecha en que se revocó el rol
   */
  revokedAt?: string;

  /**
   * Role assigned to the user in the tenant context
   */
  role?: Role;

  /**
   * Tenant associated with the role assignment
   */
  tenantId?: number;

  /**
   * User associated with the role assignment
   */
  user?: UserDto;
}
