/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Información básica del usuario autenticado
 */
export interface UserSummary {

  /**
   * Correo electrónico del usuario
   */
  email?: string;
  enabled?: boolean;

  /**
   * Identificador único del usuario
   */
  id?: number;

  /**
   * Nombre completo derivado de la entidad Person
   */
  personName?: string;

  /**
   * Tipo de persona (DOCTOR, NURSE, PATIENT, etc.)
   */
  personType?: 'DOCTOR' | 'NURSE' | 'PATIENT' | 'EMPLOYEE' | 'SUPER_ADMIN' | 'ADMIN' | 'RECEPTIONIST' | 'LAB_TECHNICIAN' | 'PHARMACIST';

  /**
   * Roles del usuario dentro del tenant actual
   */
  roles?: Array<string>;

  /**
   * Código del tenant (hospital) actual
   */
  tenantCode?: string;

  /**
   * Nombre del tenant (hospital) actual
   */
  tenantName?: string;
}
