/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRegisterRequest {
  apellidoMaterno?: string;
  apellidoPaterno: string;
  email: string;
  nombre: string;
  password: string;
  personType: 'DOCTOR' | 'NURSE' | 'PATIENT' | 'EMPLOYEE' | 'SUPER_ADMIN' | 'TENANT_ADMIN';
  segundoNombre?: string;
  tenantCode: string;
}
