/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Data Transfer Object for UserAccount entity
 */
export interface UserAccountDto {

  /**
   * UserAccount ID
   */
  id?: number;

  /**
   * Person ID
   */
  personId?: number;

  /**
   * Roles assigned in this account
   */
  roles?: Array<string>;

  /**
   * Tenant ID
   */
  tenantId?: number;

  /**
   * Tenant name
   */
  tenantName?: string;

  /**
   * User ID
   */
  userId?: number;
}
