/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { activate } from '../fn/account/activate';
import { Activate$Params } from '../fn/account/activate';
import { changePassword } from '../fn/account/change-password';
import { ChangePassword$Params } from '../fn/account/change-password';
import { deleteAccount } from '../fn/account/delete-account';
import { DeleteAccount$Params } from '../fn/account/delete-account';
import { getProfile } from '../fn/account/get-profile';
import { GetProfile$Params } from '../fn/account/get-profile';
import { requestPasswordReset } from '../fn/account/request-password-reset';
import { RequestPasswordReset$Params } from '../fn/account/request-password-reset';
import { resetPassword } from '../fn/account/reset-password';
import { ResetPassword$Params } from '../fn/account/reset-password';
import { UserSummary } from '../models/user-summary';


/**
 * Gestión de cuentas de usuario (activación, contraseñas, perfil)
 */
@Injectable({ providedIn: 'root' })
export class AccountService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `resetPassword()` */
  static readonly ResetPasswordPath = '/account/reset-password';

  /**
   * Restablecer contraseña.
   *
   * Permite restablecer la contraseña mediante un token recibido por correo
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword$Response(params: ResetPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return resetPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * Restablecer contraseña.
   *
   * Permite restablecer la contraseña mediante un token recibido por correo
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword(params: ResetPassword$Params, context?: HttpContext): Observable<void> {
    return this.resetPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `requestPasswordReset()` */
  static readonly RequestPasswordResetPath = '/account/request-reset-password';

  /**
   * Solicitar restablecimiento de contraseña.
   *
   * Envía un token o enlace para restablecer la contraseña
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `requestPasswordReset()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  requestPasswordReset$Response(params: RequestPasswordReset$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return requestPasswordReset(this.http, this.rootUrl, params, context);
  }

  /**
   * Solicitar restablecimiento de contraseña.
   *
   * Envía un token o enlace para restablecer la contraseña
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `requestPasswordReset$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  requestPasswordReset(params: RequestPasswordReset$Params, context?: HttpContext): Observable<void> {
    return this.requestPasswordReset$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `changePassword()` */
  static readonly ChangePasswordPath = '/account/change-password';

  /**
   * Cambiar contraseña.
   *
   * Permite al usuario autenticado cambiar su contraseña actual
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changePassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  changePassword$Response(params: ChangePassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return changePassword(this.http, this.rootUrl, params, context);
  }

  /**
   * Cambiar contraseña.
   *
   * Permite al usuario autenticado cambiar su contraseña actual
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changePassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  changePassword(params: ChangePassword$Params, context?: HttpContext): Observable<void> {
    return this.changePassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `activate()` */
  static readonly ActivatePath = '/account/activate';

  /**
   * Activar cuenta.
   *
   * Activa una cuenta de usuario a partir del token de activación
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  activate$Response(params: Activate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return activate(this.http, this.rootUrl, params, context);
  }

  /**
   * Activar cuenta.
   *
   * Activa una cuenta de usuario a partir del token de activación
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  activate(params: Activate$Params, context?: HttpContext): Observable<void> {
    return this.activate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getProfile()` */
  static readonly GetProfilePath = '/account/profile';

  /**
   * Obtener perfil de usuario.
   *
   * Devuelve la información básica del usuario autenticado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProfile()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProfile$Response(params?: GetProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UserSummary>> {
    return getProfile(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener perfil de usuario.
   *
   * Devuelve la información básica del usuario autenticado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProfile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProfile(params?: GetProfile$Params, context?: HttpContext): Observable<UserSummary> {
    return this.getProfile$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserSummary>): UserSummary => r.body)
    );
  }

  /** Path part for operation `deleteAccount()` */
  static readonly DeleteAccountPath = '/account';

  /**
   * Dar de baja cuenta.
   *
   * Desactiva la cuenta del usuario autenticado y cierra la sesión
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAccount$Response(params: DeleteAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * Dar de baja cuenta.
   *
   * Desactiva la cuenta del usuario autenticado y cierra la sesión
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAccount(params: DeleteAccount$Params, context?: HttpContext): Observable<void> {
    return this.deleteAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
