/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Allergy } from '../models/allergy';
import { create6 } from '../fn/allergy/create-6';
import { Create6$Params } from '../fn/allergy/create-6';
import { getAll6 } from '../fn/allergy/get-all-6';
import { GetAll6$Params } from '../fn/allergy/get-all-6';
import { getById6 } from '../fn/allergy/get-by-id-6';
import { GetById6$Params } from '../fn/allergy/get-by-id-6';


/**
 * MDM para catálogo de alergias
 */
@Injectable({ providedIn: 'root' })
export class AllergyService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `create6()` */
  static readonly Create6Path = '/mdm/allergy';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create6()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create6$Response(params: Create6$Params, context?: HttpContext): Observable<StrictHttpResponse<Allergy>> {
    return create6(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create6$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create6(params: Create6$Params, context?: HttpContext): Observable<Allergy> {
    return this.create6$Response(params, context).pipe(
      map((r: StrictHttpResponse<Allergy>): Allergy => r.body)
    );
  }

  /** Path part for operation `getById6()` */
  static readonly GetById6Path = '/mdm/allergy/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById6()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById6$Response(params: GetById6$Params, context?: HttpContext): Observable<StrictHttpResponse<Allergy>> {
    return getById6(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById6$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById6(params: GetById6$Params, context?: HttpContext): Observable<Allergy> {
    return this.getById6$Response(params, context).pipe(
      map((r: StrictHttpResponse<Allergy>): Allergy => r.body)
    );
  }

  /** Path part for operation `getAll6()` */
  static readonly GetAll6Path = '/mdm/allergy/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll6()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll6$Response(params?: GetAll6$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Allergy>>> {
    return getAll6(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll6$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll6(params?: GetAll6$Params, context?: HttpContext): Observable<Array<Allergy>> {
    return this.getAll6$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Allergy>>): Array<Allergy> => r.body)
    );
  }

}
