/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Avatar } from '../models/avatar';
import { createAvatar } from '../fn/avatar/create-avatar';
import { CreateAvatar$Params } from '../fn/avatar/create-avatar';
import { deleteAvatar } from '../fn/avatar/delete-avatar';
import { DeleteAvatar$Params } from '../fn/avatar/delete-avatar';
import { getAllAvatars } from '../fn/avatar/get-all-avatars';
import { GetAllAvatars$Params } from '../fn/avatar/get-all-avatars';
import { getAvatarById } from '../fn/avatar/get-avatar-by-id';
import { GetAvatarById$Params } from '../fn/avatar/get-avatar-by-id';
import { getAvatarImage$Jpeg } from '../fn/avatar/get-avatar-image-jpeg';
import { GetAvatarImage$Jpeg$Params } from '../fn/avatar/get-avatar-image-jpeg';
import { getAvatarImage$Png } from '../fn/avatar/get-avatar-image-png';
import { GetAvatarImage$Png$Params } from '../fn/avatar/get-avatar-image-png';
import { getPaginatedAvatars } from '../fn/avatar/get-paginated-avatars';
import { GetPaginatedAvatars$Params } from '../fn/avatar/get-paginated-avatars';
import { PageResponseDtoAvatar } from '../models/page-response-dto-avatar';
import { updateAvatar } from '../fn/avatar/update-avatar';
import { UpdateAvatar$Params } from '../fn/avatar/update-avatar';
import { uploadAvatarImage } from '../fn/avatar/upload-avatar-image';
import { UploadAvatarImage$Params } from '../fn/avatar/upload-avatar-image';


/**
 * REST API para gestionar avatares de usuarios.
 */
@Injectable({ providedIn: 'root' })
export class AvatarService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAvatarById()` */
  static readonly GetAvatarByIdPath = '/avatars/{id}';

  /**
   * Obtener un Avatar por ID.
   *
   * Devuelve un objeto Avatar por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAvatarById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAvatarById$Response(params: GetAvatarById$Params, context?: HttpContext): Observable<StrictHttpResponse<Avatar>> {
    return getAvatarById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Avatar por ID.
   *
   * Devuelve un objeto Avatar por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAvatarById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAvatarById(params: GetAvatarById$Params, context?: HttpContext): Observable<Avatar> {
    return this.getAvatarById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Avatar>): Avatar => r.body)
    );
  }

  /** Path part for operation `updateAvatar()` */
  static readonly UpdateAvatarPath = '/avatars/{id}';

  /**
   * Actualizar un Avatar por ID.
   *
   * Actualiza un Avatar existente.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAvatar()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAvatar$Response(params: UpdateAvatar$Params, context?: HttpContext): Observable<StrictHttpResponse<Avatar>> {
    return updateAvatar(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Avatar por ID.
   *
   * Actualiza un Avatar existente.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAvatar$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAvatar(params: UpdateAvatar$Params, context?: HttpContext): Observable<Avatar> {
    return this.updateAvatar$Response(params, context).pipe(
      map((r: StrictHttpResponse<Avatar>): Avatar => r.body)
    );
  }

  /** Path part for operation `deleteAvatar()` */
  static readonly DeleteAvatarPath = '/avatars/{id}';

  /**
   * Eliminar un Avatar por ID.
   *
   * Elimina un Avatar existente.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAvatar()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAvatar$Response(params: DeleteAvatar$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteAvatar(this.http, this.rootUrl, params, context);
  }

  /**
   * Eliminar un Avatar por ID.
   *
   * Elimina un Avatar existente.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAvatar$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAvatar(params: DeleteAvatar$Params, context?: HttpContext): Observable<void> {
    return this.deleteAvatar$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedAvatars()` */
  static readonly GetPaginatedAvatarsPath = '/avatars';

  /**
   * Obtiene lista paginada de Avatar.
   *
   * Devuelve lista paginada de Avatar
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedAvatars()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedAvatars$Response(params: GetPaginatedAvatars$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoAvatar>> {
    return getPaginatedAvatars(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene lista paginada de Avatar.
   *
   * Devuelve lista paginada de Avatar
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedAvatars$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedAvatars(params: GetPaginatedAvatars$Params, context?: HttpContext): Observable<PageResponseDtoAvatar> {
    return this.getPaginatedAvatars$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoAvatar>): PageResponseDtoAvatar => r.body)
    );
  }

  /** Path part for operation `createAvatar()` */
  static readonly CreateAvatarPath = '/avatars';

  /**
   * Crear un Avatar.
   *
   * Crea un nuevo Avatar.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAvatar()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAvatar$Response(params: CreateAvatar$Params, context?: HttpContext): Observable<StrictHttpResponse<Avatar>> {
    return createAvatar(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Avatar.
   *
   * Crea un nuevo Avatar.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAvatar$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAvatar(params: CreateAvatar$Params, context?: HttpContext): Observable<Avatar> {
    return this.createAvatar$Response(params, context).pipe(
      map((r: StrictHttpResponse<Avatar>): Avatar => r.body)
    );
  }

  /** Path part for operation `uploadAvatarImage()` */
  static readonly UploadAvatarImagePath = '/avatars/upload/{userId}';

  /**
   * Subir imagen de Avatar.
   *
   * Sube y actualiza la imagen del avatar para un usuario específico.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadAvatarImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadAvatarImage$Response(params: UploadAvatarImage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return uploadAvatarImage(this.http, this.rootUrl, params, context);
  }

  /**
   * Subir imagen de Avatar.
   *
   * Sube y actualiza la imagen del avatar para un usuario específico.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadAvatarImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadAvatarImage(params: UploadAvatarImage$Params, context?: HttpContext): Observable<void> {
    return this.uploadAvatarImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAvatarImage()` */
  static readonly GetAvatarImagePath = '/avatars/image/{userId}';

  /**
   * Obtener imagen de Avatar.
   *
   * Descarga la imagen del avatar de un usuario
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAvatarImage$Png()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAvatarImage$Png$Response(params: GetAvatarImage$Png$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getAvatarImage$Png(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener imagen de Avatar.
   *
   * Descarga la imagen del avatar de un usuario
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAvatarImage$Png$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAvatarImage$Png(params: GetAvatarImage$Png$Params, context?: HttpContext): Observable<string> {
    return this.getAvatarImage$Png$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /**
   * Obtener imagen de Avatar.
   *
   * Descarga la imagen del avatar de un usuario
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAvatarImage$Jpeg()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAvatarImage$Jpeg$Response(params: GetAvatarImage$Jpeg$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getAvatarImage$Jpeg(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener imagen de Avatar.
   *
   * Descarga la imagen del avatar de un usuario
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAvatarImage$Jpeg$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAvatarImage$Jpeg(params: GetAvatarImage$Jpeg$Params, context?: HttpContext): Observable<string> {
    return this.getAvatarImage$Jpeg$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getAllAvatars()` */
  static readonly GetAllAvatarsPath = '/avatars/all';

  /**
   * Obtiene todos los Avatar.
   *
   * Devuelve la lista completa de Avatar
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAvatars()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAvatars$Response(params?: GetAllAvatars$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Avatar>>> {
    return getAllAvatars(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Avatar.
   *
   * Devuelve la lista completa de Avatar
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAvatars$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAvatars(params?: GetAllAvatars$Params, context?: HttpContext): Observable<Array<Avatar>> {
    return this.getAllAvatars$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Avatar>>): Array<Avatar> => r.body)
    );
  }

}
