/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BloodType } from '../models/blood-type';
import { create5 } from '../fn/blood-type/create-5';
import { Create5$Params } from '../fn/blood-type/create-5';
import { delete3 } from '../fn/blood-type/delete-3';
import { Delete3$Params } from '../fn/blood-type/delete-3';
import { getAll5 } from '../fn/blood-type/get-all-5';
import { GetAll5$Params } from '../fn/blood-type/get-all-5';
import { getById3 } from '../fn/blood-type/get-by-id-3';
import { GetById3$Params } from '../fn/blood-type/get-by-id-3';
import { getPaginated3 } from '../fn/blood-type/get-paginated-3';
import { GetPaginated3$Params } from '../fn/blood-type/get-paginated-3';
import { PageResponseDtoBloodType } from '../models/page-response-dto-blood-type';
import { update3 } from '../fn/blood-type/update-3';
import { Update3$Params } from '../fn/blood-type/update-3';


/**
 * Gestión del catálogo maestro de tipos de sangre (MDM)
 */
@Injectable({ providedIn: 'root' })
export class BloodTypeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById3()` */
  static readonly GetById3Path = '/mdm/blood-type/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById3()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById3$Response(params: GetById3$Params, context?: HttpContext): Observable<StrictHttpResponse<BloodType>> {
    return getById3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById3(params: GetById3$Params, context?: HttpContext): Observable<BloodType> {
    return this.getById3$Response(params, context).pipe(
      map((r: StrictHttpResponse<BloodType>): BloodType => r.body)
    );
  }

  /** Path part for operation `update3()` */
  static readonly Update3Path = '/mdm/blood-type/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update3()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update3$Response(params: Update3$Params, context?: HttpContext): Observable<StrictHttpResponse<BloodType>> {
    return update3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update3$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update3(params: Update3$Params, context?: HttpContext): Observable<BloodType> {
    return this.update3$Response(params, context).pipe(
      map((r: StrictHttpResponse<BloodType>): BloodType => r.body)
    );
  }

  /** Path part for operation `delete3()` */
  static readonly Delete3Path = '/mdm/blood-type/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete3()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete3$Response(params: Delete3$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete3(params: Delete3$Params, context?: HttpContext): Observable<void> {
    return this.delete3$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginated3()` */
  static readonly GetPaginated3Path = '/mdm/blood-type';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginated3()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated3$Response(params?: GetPaginated3$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoBloodType>> {
    return getPaginated3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginated3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated3(params?: GetPaginated3$Params, context?: HttpContext): Observable<PageResponseDtoBloodType> {
    return this.getPaginated3$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoBloodType>): PageResponseDtoBloodType => r.body)
    );
  }

  /** Path part for operation `create5()` */
  static readonly Create5Path = '/mdm/blood-type';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create5()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create5$Response(params: Create5$Params, context?: HttpContext): Observable<StrictHttpResponse<BloodType>> {
    return create5(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create5$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create5(params: Create5$Params, context?: HttpContext): Observable<BloodType> {
    return this.create5$Response(params, context).pipe(
      map((r: StrictHttpResponse<BloodType>): BloodType => r.body)
    );
  }

  /** Path part for operation `getAll5()` */
  static readonly GetAll5Path = '/mdm/blood-type/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll5()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll5$Response(params?: GetAll5$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BloodType>>> {
    return getAll5(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll5$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll5(params?: GetAll5$Params, context?: HttpContext): Observable<Array<BloodType>> {
    return this.getAll5$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BloodType>>): Array<BloodType> => r.body)
    );
  }

}
