/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CivilStatus } from '../models/civil-status';
import { create4 } from '../fn/civil-status/create-4';
import { Create4$Params } from '../fn/civil-status/create-4';
import { delete2 } from '../fn/civil-status/delete-2';
import { Delete2$Params } from '../fn/civil-status/delete-2';
import { getAll4 } from '../fn/civil-status/get-all-4';
import { GetAll4$Params } from '../fn/civil-status/get-all-4';
import { getById2 } from '../fn/civil-status/get-by-id-2';
import { GetById2$Params } from '../fn/civil-status/get-by-id-2';
import { getPaginated2 } from '../fn/civil-status/get-paginated-2';
import { GetPaginated2$Params } from '../fn/civil-status/get-paginated-2';
import { PageResponseDtoCivilStatus } from '../models/page-response-dto-civil-status';
import { update2 } from '../fn/civil-status/update-2';
import { Update2$Params } from '../fn/civil-status/update-2';


/**
 * Gestión del catálogo maestro de estado civil (MDM)
 */
@Injectable({ providedIn: 'root' })
export class CivilStatusService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById2()` */
  static readonly GetById2Path = '/mdm/demographic/civil-status/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById2()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById2$Response(params: GetById2$Params, context?: HttpContext): Observable<StrictHttpResponse<CivilStatus>> {
    return getById2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById2(params: GetById2$Params, context?: HttpContext): Observable<CivilStatus> {
    return this.getById2$Response(params, context).pipe(
      map((r: StrictHttpResponse<CivilStatus>): CivilStatus => r.body)
    );
  }

  /** Path part for operation `update2()` */
  static readonly Update2Path = '/mdm/demographic/civil-status/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2$Response(params: Update2$Params, context?: HttpContext): Observable<StrictHttpResponse<CivilStatus>> {
    return update2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2(params: Update2$Params, context?: HttpContext): Observable<CivilStatus> {
    return this.update2$Response(params, context).pipe(
      map((r: StrictHttpResponse<CivilStatus>): CivilStatus => r.body)
    );
  }

  /** Path part for operation `delete2()` */
  static readonly Delete2Path = '/mdm/demographic/civil-status/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete2()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2$Response(params: Delete2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2(params: Delete2$Params, context?: HttpContext): Observable<void> {
    return this.delete2$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginated2()` */
  static readonly GetPaginated2Path = '/mdm/demographic/civil-status';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginated2()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated2$Response(params: GetPaginated2$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoCivilStatus>> {
    return getPaginated2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginated2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated2(params: GetPaginated2$Params, context?: HttpContext): Observable<PageResponseDtoCivilStatus> {
    return this.getPaginated2$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoCivilStatus>): PageResponseDtoCivilStatus => r.body)
    );
  }

  /** Path part for operation `create4()` */
  static readonly Create4Path = '/mdm/demographic/civil-status';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create4()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create4$Response(params: Create4$Params, context?: HttpContext): Observable<StrictHttpResponse<CivilStatus>> {
    return create4(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create4$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create4(params: Create4$Params, context?: HttpContext): Observable<CivilStatus> {
    return this.create4$Response(params, context).pipe(
      map((r: StrictHttpResponse<CivilStatus>): CivilStatus => r.body)
    );
  }

  /** Path part for operation `getAll4()` */
  static readonly GetAll4Path = '/mdm/demographic/civil-status/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll4()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll4$Response(params?: GetAll4$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CivilStatus>>> {
    return getAll4(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll4$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll4(params?: GetAll4$Params, context?: HttpContext): Observable<Array<CivilStatus>> {
    return this.getAll4$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CivilStatus>>): Array<CivilStatus> => r.body)
    );
  }

}
