/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createEmployee } from '../fn/employee/create-employee';
import { CreateEmployee$Params } from '../fn/employee/create-employee';
import { deleteEmployee } from '../fn/employee/delete-employee';
import { DeleteEmployee$Params } from '../fn/employee/delete-employee';
import { Employee } from '../models/employee';
import { getAllEmployees } from '../fn/employee/get-all-employees';
import { GetAllEmployees$Params } from '../fn/employee/get-all-employees';
import { getEmployeeById } from '../fn/employee/get-employee-by-id';
import { GetEmployeeById$Params } from '../fn/employee/get-employee-by-id';
import { getPaginatedEmployees } from '../fn/employee/get-paginated-employees';
import { GetPaginatedEmployees$Params } from '../fn/employee/get-paginated-employees';
import { PageResponseDtoEmployee } from '../models/page-response-dto-employee';
import { updateEmployee } from '../fn/employee/update-employee';
import { UpdateEmployee$Params } from '../fn/employee/update-employee';


/**
 * Gestión de personal médico y administrativo (Employees)
 */
@Injectable({ providedIn: 'root' })
export class EmployeeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getEmployeeById()` */
  static readonly GetEmployeeByIdPath = '/employees/{id}';

  /**
   * Obtener empleado por ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEmployeeById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeById$Response(params: GetEmployeeById$Params, context?: HttpContext): Observable<StrictHttpResponse<Employee>> {
    return getEmployeeById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener empleado por ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEmployeeById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEmployeeById(params: GetEmployeeById$Params, context?: HttpContext): Observable<Employee> {
    return this.getEmployeeById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Employee>): Employee => r.body)
    );
  }

  /** Path part for operation `updateEmployee()` */
  static readonly UpdateEmployeePath = '/employees/{id}';

  /**
   * Actualizar empleado existente.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEmployee()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployee$Response(params: UpdateEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<Employee>> {
    return updateEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar empleado existente.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEmployee$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEmployee(params: UpdateEmployee$Params, context?: HttpContext): Observable<Employee> {
    return this.updateEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<Employee>): Employee => r.body)
    );
  }

  /** Path part for operation `deleteEmployee()` */
  static readonly DeleteEmployeePath = '/employees/{id}';

  /**
   * Eliminar empleado (borrado lógico).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEmployee()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEmployee$Response(params: DeleteEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * Eliminar empleado (borrado lógico).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEmployee$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEmployee(params: DeleteEmployee$Params, context?: HttpContext): Observable<void> {
    return this.deleteEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedEmployees()` */
  static readonly GetPaginatedEmployeesPath = '/employees';

  /**
   * Obtener empleados paginados con filtros.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedEmployees()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedEmployees$Response(params?: GetPaginatedEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoEmployee>> {
    return getPaginatedEmployees(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener empleados paginados con filtros.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedEmployees$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedEmployees(params?: GetPaginatedEmployees$Params, context?: HttpContext): Observable<PageResponseDtoEmployee> {
    return this.getPaginatedEmployees$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoEmployee>): PageResponseDtoEmployee => r.body)
    );
  }

  /** Path part for operation `createEmployee()` */
  static readonly CreateEmployeePath = '/employees';

  /**
   * Crear nuevo empleado.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEmployee()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee$Response(params: CreateEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<Employee>> {
    return createEmployee(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear nuevo empleado.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEmployee$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEmployee(params: CreateEmployee$Params, context?: HttpContext): Observable<Employee> {
    return this.createEmployee$Response(params, context).pipe(
      map((r: StrictHttpResponse<Employee>): Employee => r.body)
    );
  }

  /** Path part for operation `getAllEmployees()` */
  static readonly GetAllEmployeesPath = '/employees/all';

  /**
   * Obtener todos los empleados.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllEmployees()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllEmployees$Response(params?: GetAllEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Employee>>> {
    return getAllEmployees(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener todos los empleados.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllEmployees$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllEmployees(params?: GetAllEmployees$Params, context?: HttpContext): Observable<Array<Employee>> {
    return this.getAllEmployees$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Employee>>): Array<Employee> => r.body)
    );
  }

}
