/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create3 } from '../fn/gender/create-3';
import { Create3$Params } from '../fn/gender/create-3';
import { delete1 } from '../fn/gender/delete-1';
import { Delete1$Params } from '../fn/gender/delete-1';
import { Gender } from '../models/gender';
import { getAll3 } from '../fn/gender/get-all-3';
import { GetAll3$Params } from '../fn/gender/get-all-3';
import { getById1 } from '../fn/gender/get-by-id-1';
import { GetById1$Params } from '../fn/gender/get-by-id-1';
import { getPaginated1 } from '../fn/gender/get-paginated-1';
import { GetPaginated1$Params } from '../fn/gender/get-paginated-1';
import { PageResponseDtoGender } from '../models/page-response-dto-gender';
import { update1 } from '../fn/gender/update-1';
import { Update1$Params } from '../fn/gender/update-1';


/**
 * Gestión del catálogo maestro de géneros (MDM)
 */
@Injectable({ providedIn: 'root' })
export class GenderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById1()` */
  static readonly GetById1Path = '/mdm/demographic/gender/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById1$Response(params: GetById1$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
    return getById1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById1(params: GetById1$Params, context?: HttpContext): Observable<Gender> {
    return this.getById1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Gender>): Gender => r.body)
    );
  }

  /** Path part for operation `update1()` */
  static readonly Update1Path = '/mdm/demographic/gender/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update1$Response(params: Update1$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
    return update1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update1(params: Update1$Params, context?: HttpContext): Observable<Gender> {
    return this.update1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Gender>): Gender => r.body)
    );
  }

  /** Path part for operation `delete1()` */
  static readonly Delete1Path = '/mdm/demographic/gender/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete1()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete1$Response(params: Delete1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete1(params: Delete1$Params, context?: HttpContext): Observable<void> {
    return this.delete1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginated1()` */
  static readonly GetPaginated1Path = '/mdm/demographic/gender';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginated1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated1$Response(params: GetPaginated1$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoGender>> {
    return getPaginated1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginated1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated1(params: GetPaginated1$Params, context?: HttpContext): Observable<PageResponseDtoGender> {
    return this.getPaginated1$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoGender>): PageResponseDtoGender => r.body)
    );
  }

  /** Path part for operation `create3()` */
  static readonly Create3Path = '/mdm/demographic/gender';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create3()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create3$Response(params: Create3$Params, context?: HttpContext): Observable<StrictHttpResponse<Gender>> {
    return create3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create3$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create3(params: Create3$Params, context?: HttpContext): Observable<Gender> {
    return this.create3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Gender>): Gender => r.body)
    );
  }

  /** Path part for operation `getAll3()` */
  static readonly GetAll3Path = '/mdm/demographic/gender/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll3()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll3$Response(params?: GetAll3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Gender>>> {
    return getAll3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll3(params?: GetAll3$Params, context?: HttpContext): Observable<Array<Gender>> {
    return this.getAll3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Gender>>): Array<Gender> => r.body)
    );
  }

}
