/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProvider } from '../fn/healthcare-provider/create-provider';
import { CreateProvider$Params } from '../fn/healthcare-provider/create-provider';
import { deleteProvider } from '../fn/healthcare-provider/delete-provider';
import { DeleteProvider$Params } from '../fn/healthcare-provider/delete-provider';
import { getAllProviders } from '../fn/healthcare-provider/get-all-providers';
import { GetAllProviders$Params } from '../fn/healthcare-provider/get-all-providers';
import { getPaginatedProviders } from '../fn/healthcare-provider/get-paginated-providers';
import { GetPaginatedProviders$Params } from '../fn/healthcare-provider/get-paginated-providers';
import { getProviderById } from '../fn/healthcare-provider/get-provider-by-id';
import { GetProviderById$Params } from '../fn/healthcare-provider/get-provider-by-id';
import { HealthcareProvider } from '../models/healthcare-provider';
import { PageResponseDtoHealthcareProvider } from '../models/page-response-dto-healthcare-provider';
import { updateProvider } from '../fn/healthcare-provider/update-provider';
import { UpdateProvider$Params } from '../fn/healthcare-provider/update-provider';


/**
 * REST API para gestionar el catálogo de aseguradoras y pagadores de salud (MDM).
 */
@Injectable({ providedIn: 'root' })
export class HealthcareProviderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getProviderById()` */
  static readonly GetProviderByIdPath = '/mdm/healthcare-provider/{id}';

  /**
   * Obtener un Healthcare Provider por ID.
   *
   * Devuelve un objeto Healthcare Provider por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProviderById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProviderById$Response(params: GetProviderById$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthcareProvider>> {
    return getProviderById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Healthcare Provider por ID.
   *
   * Devuelve un objeto Healthcare Provider por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProviderById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProviderById(params: GetProviderById$Params, context?: HttpContext): Observable<HealthcareProvider> {
    return this.getProviderById$Response(params, context).pipe(
      map((r: StrictHttpResponse<HealthcareProvider>): HealthcareProvider => r.body)
    );
  }

  /** Path part for operation `updateProvider()` */
  static readonly UpdateProviderPath = '/mdm/healthcare-provider/{id}';

  /**
   * Actualizar un Healthcare Provider por ID.
   *
   * Actualiza un Healthcare Provider existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProvider()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProvider$Response(params: UpdateProvider$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthcareProvider>> {
    return updateProvider(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Healthcare Provider por ID.
   *
   * Actualiza un Healthcare Provider existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProvider$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProvider(params: UpdateProvider$Params, context?: HttpContext): Observable<HealthcareProvider> {
    return this.updateProvider$Response(params, context).pipe(
      map((r: StrictHttpResponse<HealthcareProvider>): HealthcareProvider => r.body)
    );
  }

  /** Path part for operation `deleteProvider()` */
  static readonly DeleteProviderPath = '/mdm/healthcare-provider/{id}';

  /**
   * Healthcare Provider a eliminar por ID.
   *
   * Elimina un Healthcare Provider existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProvider()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProvider$Response(params: DeleteProvider$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProvider(this.http, this.rootUrl, params, context);
  }

  /**
   * Healthcare Provider a eliminar por ID.
   *
   * Elimina un Healthcare Provider existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProvider$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProvider(params: DeleteProvider$Params, context?: HttpContext): Observable<void> {
    return this.deleteProvider$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedProviders()` */
  static readonly GetPaginatedProvidersPath = '/mdm/healthcare-provider';

  /**
   * Obtiene una lista paginada de Healthcare Provider.
   *
   * Devuelve una lista paginada de Healthcare Provider
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedProviders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProviders$Response(params: GetPaginatedProviders$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoHealthcareProvider>> {
    return getPaginatedProviders(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Healthcare Provider.
   *
   * Devuelve una lista paginada de Healthcare Provider
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedProviders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProviders(params: GetPaginatedProviders$Params, context?: HttpContext): Observable<PageResponseDtoHealthcareProvider> {
    return this.getPaginatedProviders$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoHealthcareProvider>): PageResponseDtoHealthcareProvider => r.body)
    );
  }

  /** Path part for operation `createProvider()` */
  static readonly CreateProviderPath = '/mdm/healthcare-provider';

  /**
   * Crear un Healthcare Provider.
   *
   * Crea un nuevo Healthcare Provider usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProvider()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProvider$Response(params: CreateProvider$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthcareProvider>> {
    return createProvider(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Healthcare Provider.
   *
   * Crea un nuevo Healthcare Provider usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProvider$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProvider(params: CreateProvider$Params, context?: HttpContext): Observable<HealthcareProvider> {
    return this.createProvider$Response(params, context).pipe(
      map((r: StrictHttpResponse<HealthcareProvider>): HealthcareProvider => r.body)
    );
  }

  /** Path part for operation `getAllProviders()` */
  static readonly GetAllProvidersPath = '/mdm/healthcare-provider/all';

  /**
   * Obtiene todos los Healthcare Provider.
   *
   * Devuelve la lista completa de Healthcare Provider
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllProviders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProviders$Response(params?: GetAllProviders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HealthcareProvider>>> {
    return getAllProviders(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Healthcare Provider.
   *
   * Devuelve la lista completa de Healthcare Provider
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllProviders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProviders(params?: GetAllProviders$Params, context?: HttpContext): Observable<Array<HealthcareProvider>> {
    return this.getAllProviders$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<HealthcareProvider>>): Array<HealthcareProvider> => r.body)
    );
  }

}
