/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createHospital } from '../fn/hospital/create-hospital';
import { CreateHospital$Params } from '../fn/hospital/create-hospital';
import { deleteHospital } from '../fn/hospital/delete-hospital';
import { DeleteHospital$Params } from '../fn/hospital/delete-hospital';
import { getAllHospitals } from '../fn/hospital/get-all-hospitals';
import { GetAllHospitals$Params } from '../fn/hospital/get-all-hospitals';
import { getHospitalById } from '../fn/hospital/get-hospital-by-id';
import { GetHospitalById$Params } from '../fn/hospital/get-hospital-by-id';
import { getPaginatedHospitals } from '../fn/hospital/get-paginated-hospitals';
import { GetPaginatedHospitals$Params } from '../fn/hospital/get-paginated-hospitals';
import { Hospital } from '../models/hospital';
import { PageResponseDtoHospital } from '../models/page-response-dto-hospital';
import { updateHospital } from '../fn/hospital/update-hospital';
import { UpdateHospital$Params } from '../fn/hospital/update-hospital';


/**
 * REST API to manage professional Hospital details: create, update, retrieve and delete.
 */
@Injectable({ providedIn: 'root' })
export class HospitalService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getHospitalById()` */
  static readonly GetHospitalByIdPath = '/hospitals/{id}';

  /**
   * Get a Hospital by ID.
   *
   * Returns a Hospital object by specified ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHospitalById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHospitalById$Response(params: GetHospitalById$Params, context?: HttpContext): Observable<StrictHttpResponse<Hospital>> {
    return getHospitalById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a Hospital by ID.
   *
   * Returns a Hospital object by specified ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHospitalById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHospitalById(params: GetHospitalById$Params, context?: HttpContext): Observable<Hospital> {
    return this.getHospitalById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Hospital>): Hospital => r.body)
    );
  }

  /** Path part for operation `updateHospital()` */
  static readonly UpdateHospitalPath = '/hospitals/{id}';

  /**
   * Update a Hospital by ID.
   *
   * Updates an existing Hospital using its ID and provided data.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateHospital()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateHospital$Response(params: UpdateHospital$Params, context?: HttpContext): Observable<StrictHttpResponse<Hospital>> {
    return updateHospital(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a Hospital by ID.
   *
   * Updates an existing Hospital using its ID and provided data.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateHospital$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateHospital(params: UpdateHospital$Params, context?: HttpContext): Observable<Hospital> {
    return this.updateHospital$Response(params, context).pipe(
      map((r: StrictHttpResponse<Hospital>): Hospital => r.body)
    );
  }

  /** Path part for operation `deleteHospital()` */
  static readonly DeleteHospitalPath = '/hospitals/{id}';

  /**
   * Hospital to delete by ID.
   *
   * Deletes an existing Hospital using its ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteHospital()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteHospital$Response(params: DeleteHospital$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteHospital(this.http, this.rootUrl, params, context);
  }

  /**
   * Hospital to delete by ID.
   *
   * Deletes an existing Hospital using its ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteHospital$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteHospital(params: DeleteHospital$Params, context?: HttpContext): Observable<void> {
    return this.deleteHospital$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedHospitals()` */
  static readonly GetPaginatedHospitalsPath = '/hospitals';

  /**
   * Get a paginated list of Hospital.
   *
   * Returns a paginated list of Hospital
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedHospitals()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedHospitals$Response(params?: GetPaginatedHospitals$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoHospital>> {
    return getPaginatedHospitals(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a paginated list of Hospital.
   *
   * Returns a paginated list of Hospital
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedHospitals$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedHospitals(params?: GetPaginatedHospitals$Params, context?: HttpContext): Observable<PageResponseDtoHospital> {
    return this.getPaginatedHospitals$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoHospital>): PageResponseDtoHospital => r.body)
    );
  }

  /** Path part for operation `createHospital()` */
  static readonly CreateHospitalPath = '/hospitals';

  /**
   * Create a Hospital.
   *
   * Creates a new Hospital using providing data in the request body.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createHospital()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createHospital$Response(params: CreateHospital$Params, context?: HttpContext): Observable<StrictHttpResponse<Hospital>> {
    return createHospital(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a Hospital.
   *
   * Creates a new Hospital using providing data in the request body.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createHospital$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createHospital(params: CreateHospital$Params, context?: HttpContext): Observable<Hospital> {
    return this.createHospital$Response(params, context).pipe(
      map((r: StrictHttpResponse<Hospital>): Hospital => r.body)
    );
  }

  /** Path part for operation `getAllHospitals()` */
  static readonly GetAllHospitalsPath = '/hospitals/all';

  /**
   * Get all Hospital.
   *
   * Returns the complete list of Hospital
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllHospitals()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllHospitals$Response(params?: GetAllHospitals$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Hospital>>> {
    return getAllHospitals(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all Hospital.
   *
   * Returns the complete list of Hospital
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllHospitals$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllHospitals(params?: GetAllHospitals$Params, context?: HttpContext): Observable<Array<Hospital>> {
    return this.getAllHospitals$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Hospital>>): Array<Hospital> => r.body)
    );
  }

}
