/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createIcd10 } from '../fn/icd-10-diagnosis/create-icd-10';
import { CreateIcd10$Params } from '../fn/icd-10-diagnosis/create-icd-10';
import { deleteIcd10 } from '../fn/icd-10-diagnosis/delete-icd-10';
import { DeleteIcd10$Params } from '../fn/icd-10-diagnosis/delete-icd-10';
import { getAllIcd10 } from '../fn/icd-10-diagnosis/get-all-icd-10';
import { GetAllIcd10$Params } from '../fn/icd-10-diagnosis/get-all-icd-10';
import { getIcd10ById } from '../fn/icd-10-diagnosis/get-icd-10-by-id';
import { GetIcd10ById$Params } from '../fn/icd-10-diagnosis/get-icd-10-by-id';
import { getPaginatedIcd10 } from '../fn/icd-10-diagnosis/get-paginated-icd-10';
import { GetPaginatedIcd10$Params } from '../fn/icd-10-diagnosis/get-paginated-icd-10';
import { Icd10 } from '../models/icd-10';
import { PageResponseDtoIcd10 } from '../models/page-response-dto-icd-10';
import { updateIcd10 } from '../fn/icd-10-diagnosis/update-icd-10';
import { UpdateIcd10$Params } from '../fn/icd-10-diagnosis/update-icd-10';


/**
 * REST API para gestionar el catálogo de diagnósticos CIE-10 (MDM).
 */
@Injectable({ providedIn: 'root' })
export class Icd10DiagnosisService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getIcd10ById()` */
  static readonly GetIcd10ByIdPath = '/mdm/diagnosis/{id}';

  /**
   * Obtener un ICD-10 Diagnosis por ID.
   *
   * Devuelve un objeto ICD-10 Diagnosis por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getIcd10ById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIcd10ById$Response(params: GetIcd10ById$Params, context?: HttpContext): Observable<StrictHttpResponse<Icd10>> {
    return getIcd10ById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un ICD-10 Diagnosis por ID.
   *
   * Devuelve un objeto ICD-10 Diagnosis por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getIcd10ById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIcd10ById(params: GetIcd10ById$Params, context?: HttpContext): Observable<Icd10> {
    return this.getIcd10ById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Icd10>): Icd10 => r.body)
    );
  }

  /** Path part for operation `updateIcd10()` */
  static readonly UpdateIcd10Path = '/mdm/diagnosis/{id}';

  /**
   * Actualizar un ICD-10 Diagnosis por ID.
   *
   * Actualiza un ICD-10 Diagnosis existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateIcd10()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIcd10$Response(params: UpdateIcd10$Params, context?: HttpContext): Observable<StrictHttpResponse<Icd10>> {
    return updateIcd10(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un ICD-10 Diagnosis por ID.
   *
   * Actualiza un ICD-10 Diagnosis existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateIcd10$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIcd10(params: UpdateIcd10$Params, context?: HttpContext): Observable<Icd10> {
    return this.updateIcd10$Response(params, context).pipe(
      map((r: StrictHttpResponse<Icd10>): Icd10 => r.body)
    );
  }

  /** Path part for operation `deleteIcd10()` */
  static readonly DeleteIcd10Path = '/mdm/diagnosis/{id}';

  /**
   * ICD-10 Diagnosis a eliminar por ID.
   *
   * Elimina un ICD-10 Diagnosis existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteIcd10()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteIcd10$Response(params: DeleteIcd10$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteIcd10(this.http, this.rootUrl, params, context);
  }

  /**
   * ICD-10 Diagnosis a eliminar por ID.
   *
   * Elimina un ICD-10 Diagnosis existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteIcd10$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteIcd10(params: DeleteIcd10$Params, context?: HttpContext): Observable<void> {
    return this.deleteIcd10$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedIcd10()` */
  static readonly GetPaginatedIcd10Path = '/mdm/diagnosis';

  /**
   * Obtiene una lista paginada de ICD-10 Diagnosis.
   *
   * Devuelve una lista paginada de ICD-10 Diagnosis
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedIcd10()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedIcd10$Response(params: GetPaginatedIcd10$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoIcd10>> {
    return getPaginatedIcd10(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de ICD-10 Diagnosis.
   *
   * Devuelve una lista paginada de ICD-10 Diagnosis
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedIcd10$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedIcd10(params: GetPaginatedIcd10$Params, context?: HttpContext): Observable<PageResponseDtoIcd10> {
    return this.getPaginatedIcd10$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoIcd10>): PageResponseDtoIcd10 => r.body)
    );
  }

  /** Path part for operation `createIcd10()` */
  static readonly CreateIcd10Path = '/mdm/diagnosis';

  /**
   * Crear un ICD-10 Diagnosis.
   *
   * Crea un nuevo ICD-10 Diagnosis usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createIcd10()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createIcd10$Response(params: CreateIcd10$Params, context?: HttpContext): Observable<StrictHttpResponse<Icd10>> {
    return createIcd10(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un ICD-10 Diagnosis.
   *
   * Crea un nuevo ICD-10 Diagnosis usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createIcd10$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createIcd10(params: CreateIcd10$Params, context?: HttpContext): Observable<Icd10> {
    return this.createIcd10$Response(params, context).pipe(
      map((r: StrictHttpResponse<Icd10>): Icd10 => r.body)
    );
  }

  /** Path part for operation `getAllIcd10()` */
  static readonly GetAllIcd10Path = '/mdm/diagnosis/all';

  /**
   * Obtiene todos los ICD-10 Diagnosis.
   *
   * Devuelve la lista completa de ICD-10 Diagnosis
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllIcd10()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllIcd10$Response(params?: GetAllIcd10$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Icd10>>> {
    return getAllIcd10(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los ICD-10 Diagnosis.
   *
   * Devuelve la lista completa de ICD-10 Diagnosis
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllIcd10$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllIcd10(params?: GetAllIcd10$Params, context?: HttpContext): Observable<Array<Icd10>> {
    return this.getAllIcd10$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Icd10>>): Array<Icd10> => r.body)
    );
  }

}
