/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create2 } from '../fn/identification-type/create-2';
import { Create2$Params } from '../fn/identification-type/create-2';
import { delete4 } from '../fn/identification-type/delete-4';
import { Delete4$Params } from '../fn/identification-type/delete-4';
import { getAll2 } from '../fn/identification-type/get-all-2';
import { GetAll2$Params } from '../fn/identification-type/get-all-2';
import { getById5 } from '../fn/identification-type/get-by-id-5';
import { GetById5$Params } from '../fn/identification-type/get-by-id-5';
import { IdentificationType } from '../models/identification-type';


/**
 * MDM para tipos de identificación
 */
@Injectable({ providedIn: 'root' })
export class IdentificationTypeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `create2()` */
  static readonly Create2Path = '/mdm/identification-type';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2$Response(params: Create2$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentificationType>> {
    return create2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2(params: Create2$Params, context?: HttpContext): Observable<IdentificationType> {
    return this.create2$Response(params, context).pipe(
      map((r: StrictHttpResponse<IdentificationType>): IdentificationType => r.body)
    );
  }

  /** Path part for operation `getById5()` */
  static readonly GetById5Path = '/mdm/identification-type/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById5()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById5$Response(params: GetById5$Params, context?: HttpContext): Observable<StrictHttpResponse<IdentificationType>> {
    return getById5(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById5$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById5(params: GetById5$Params, context?: HttpContext): Observable<IdentificationType> {
    return this.getById5$Response(params, context).pipe(
      map((r: StrictHttpResponse<IdentificationType>): IdentificationType => r.body)
    );
  }

  /** Path part for operation `delete4()` */
  static readonly Delete4Path = '/mdm/identification-type/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete4()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete4$Response(params: Delete4$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete4(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete4$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete4(params: Delete4$Params, context?: HttpContext): Observable<void> {
    return this.delete4$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAll2()` */
  static readonly GetAll2Path = '/mdm/identification-type/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll2()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll2$Response(params?: GetAll2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IdentificationType>>> {
    return getAll2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll2(params?: GetAll2$Params, context?: HttpContext): Observable<Array<IdentificationType>> {
    return this.getAll2$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<IdentificationType>>): Array<IdentificationType> => r.body)
    );
  }

}
