/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create1 } from '../fn/kinship/create-1';
import { Create1$Params } from '../fn/kinship/create-1';
import { delete$ } from '../fn/kinship/delete';
import { Delete$Params } from '../fn/kinship/delete';
import { getAll1 } from '../fn/kinship/get-all-1';
import { GetAll1$Params } from '../fn/kinship/get-all-1';
import { getById } from '../fn/kinship/get-by-id';
import { GetById$Params } from '../fn/kinship/get-by-id';
import { getPaginated } from '../fn/kinship/get-paginated';
import { GetPaginated$Params } from '../fn/kinship/get-paginated';
import { Kinship } from '../models/kinship';
import { PageResponseDtoKinship } from '../models/page-response-dto-kinship';
import { update } from '../fn/kinship/update';
import { Update$Params } from '../fn/kinship/update';


/**
 * Gestión del catálogo maestro de parentescos (MDM)
 */
@Injectable({ providedIn: 'root' })
export class KinshipService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/mdm/kinship/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<Kinship> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Kinship>): Kinship => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/mdm/kinship/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<Kinship> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<Kinship>): Kinship => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/mdm/kinship/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginated()` */
  static readonly GetPaginatedPath = '/mdm/kinship';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginated()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated$Response(params?: GetPaginated$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoKinship>> {
    return getPaginated(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginated$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginated(params?: GetPaginated$Params, context?: HttpContext): Observable<PageResponseDtoKinship> {
    return this.getPaginated$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoKinship>): PageResponseDtoKinship => r.body)
    );
  }

  /** Path part for operation `create1()` */
  static readonly Create1Path = '/mdm/kinship';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create1$Response(params: Create1$Params, context?: HttpContext): Observable<StrictHttpResponse<Kinship>> {
    return create1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create1(params: Create1$Params, context?: HttpContext): Observable<Kinship> {
    return this.create1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Kinship>): Kinship => r.body)
    );
  }

  /** Path part for operation `getAll1()` */
  static readonly GetAll1Path = '/mdm/kinship/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll1$Response(params?: GetAll1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Kinship>>> {
    return getAll1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll1(params?: GetAll1$Params, context?: HttpContext): Observable<Array<Kinship>> {
    return this.getAll1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Kinship>>): Array<Kinship> => r.body)
    );
  }

}
