/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createSpecialty } from '../fn/medical-specialty/create-specialty';
import { CreateSpecialty$Params } from '../fn/medical-specialty/create-specialty';
import { deleteSpecialty } from '../fn/medical-specialty/delete-specialty';
import { DeleteSpecialty$Params } from '../fn/medical-specialty/delete-specialty';
import { getAllSpecialties } from '../fn/medical-specialty/get-all-specialties';
import { GetAllSpecialties$Params } from '../fn/medical-specialty/get-all-specialties';
import { getPaginatedSpecialties } from '../fn/medical-specialty/get-paginated-specialties';
import { GetPaginatedSpecialties$Params } from '../fn/medical-specialty/get-paginated-specialties';
import { getSpecialtyById } from '../fn/medical-specialty/get-specialty-by-id';
import { GetSpecialtyById$Params } from '../fn/medical-specialty/get-specialty-by-id';
import { MedicalSpecialty } from '../models/medical-specialty';
import { PageResponseDtoMedicalSpecialty } from '../models/page-response-dto-medical-specialty';
import { updateSpecialty } from '../fn/medical-specialty/update-specialty';
import { UpdateSpecialty$Params } from '../fn/medical-specialty/update-specialty';


/**
 * REST API para gestionar el catálogo maestro de especialidades médicas (MDM).
 */
@Injectable({ providedIn: 'root' })
export class MedicalSpecialtyService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getSpecialtyById()` */
  static readonly GetSpecialtyByIdPath = '/mdm/medical-specialty/{id}';

  /**
   * Obtener un Medical Specialty por ID.
   *
   * Devuelve un objeto Medical Specialty por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSpecialtyById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecialtyById$Response(params: GetSpecialtyById$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalSpecialty>> {
    return getSpecialtyById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Medical Specialty por ID.
   *
   * Devuelve un objeto Medical Specialty por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSpecialtyById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSpecialtyById(params: GetSpecialtyById$Params, context?: HttpContext): Observable<MedicalSpecialty> {
    return this.getSpecialtyById$Response(params, context).pipe(
      map((r: StrictHttpResponse<MedicalSpecialty>): MedicalSpecialty => r.body)
    );
  }

  /** Path part for operation `updateSpecialty()` */
  static readonly UpdateSpecialtyPath = '/mdm/medical-specialty/{id}';

  /**
   * Actualizar un Medical Specialty por ID.
   *
   * Actualiza un Medical Specialty existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSpecialty()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSpecialty$Response(params: UpdateSpecialty$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalSpecialty>> {
    return updateSpecialty(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Medical Specialty por ID.
   *
   * Actualiza un Medical Specialty existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSpecialty$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSpecialty(params: UpdateSpecialty$Params, context?: HttpContext): Observable<MedicalSpecialty> {
    return this.updateSpecialty$Response(params, context).pipe(
      map((r: StrictHttpResponse<MedicalSpecialty>): MedicalSpecialty => r.body)
    );
  }

  /** Path part for operation `deleteSpecialty()` */
  static readonly DeleteSpecialtyPath = '/mdm/medical-specialty/{id}';

  /**
   * Medical Specialty a eliminar por ID.
   *
   * Elimina un Medical Specialty existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSpecialty()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSpecialty$Response(params: DeleteSpecialty$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteSpecialty(this.http, this.rootUrl, params, context);
  }

  /**
   * Medical Specialty a eliminar por ID.
   *
   * Elimina un Medical Specialty existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSpecialty$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSpecialty(params: DeleteSpecialty$Params, context?: HttpContext): Observable<void> {
    return this.deleteSpecialty$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedSpecialties()` */
  static readonly GetPaginatedSpecialtiesPath = '/mdm/medical-specialty';

  /**
   * Obtiene una lista paginada de Medical Specialty.
   *
   * Devuelve una lista paginada de Medical Specialty
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedSpecialties()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedSpecialties$Response(params?: GetPaginatedSpecialties$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoMedicalSpecialty>> {
    return getPaginatedSpecialties(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Medical Specialty.
   *
   * Devuelve una lista paginada de Medical Specialty
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedSpecialties$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedSpecialties(params?: GetPaginatedSpecialties$Params, context?: HttpContext): Observable<PageResponseDtoMedicalSpecialty> {
    return this.getPaginatedSpecialties$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoMedicalSpecialty>): PageResponseDtoMedicalSpecialty => r.body)
    );
  }

  /** Path part for operation `createSpecialty()` */
  static readonly CreateSpecialtyPath = '/mdm/medical-specialty';

  /**
   * Crear un Medical Specialty.
   *
   * Crea un nuevo Medical Specialty usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSpecialty()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSpecialty$Response(params: CreateSpecialty$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalSpecialty>> {
    return createSpecialty(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Medical Specialty.
   *
   * Crea un nuevo Medical Specialty usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSpecialty$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSpecialty(params: CreateSpecialty$Params, context?: HttpContext): Observable<MedicalSpecialty> {
    return this.createSpecialty$Response(params, context).pipe(
      map((r: StrictHttpResponse<MedicalSpecialty>): MedicalSpecialty => r.body)
    );
  }

  /** Path part for operation `getAllSpecialties()` */
  static readonly GetAllSpecialtiesPath = '/mdm/medical-specialty/all';

  /**
   * Obtiene todos los Medical Specialty.
   *
   * Devuelve la lista completa de Medical Specialty
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllSpecialties()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSpecialties$Response(params?: GetAllSpecialties$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MedicalSpecialty>>> {
    return getAllSpecialties(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Medical Specialty.
   *
   * Devuelve la lista completa de Medical Specialty
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllSpecialties$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSpecialties(params?: GetAllSpecialties$Params, context?: HttpContext): Observable<Array<MedicalSpecialty>> {
    return this.getAllSpecialties$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MedicalSpecialty>>): Array<MedicalSpecialty> => r.body)
    );
  }

}
