/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProcedure } from '../fn/medical-procedure/create-procedure';
import { CreateProcedure$Params } from '../fn/medical-procedure/create-procedure';
import { deleteProcedure } from '../fn/medical-procedure/delete-procedure';
import { DeleteProcedure$Params } from '../fn/medical-procedure/delete-procedure';
import { getAllProcedures } from '../fn/medical-procedure/get-all-procedures';
import { GetAllProcedures$Params } from '../fn/medical-procedure/get-all-procedures';
import { getPaginatedProcedures } from '../fn/medical-procedure/get-paginated-procedures';
import { GetPaginatedProcedures$Params } from '../fn/medical-procedure/get-paginated-procedures';
import { getProcedureById } from '../fn/medical-procedure/get-procedure-by-id';
import { GetProcedureById$Params } from '../fn/medical-procedure/get-procedure-by-id';
import { MedicalProcedure } from '../models/medical-procedure';
import { PageResponseDtoMedicalProcedure } from '../models/page-response-dto-medical-procedure';
import { updateProcedure } from '../fn/medical-procedure/update-procedure';
import { UpdateProcedure$Params } from '../fn/medical-procedure/update-procedure';


/**
 * REST API para gestionar el catálogo de procedimientos médicos y laboratorios (MDM).
 */
@Injectable({ providedIn: 'root' })
export class MedicalProcedureService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getProcedureById()` */
  static readonly GetProcedureByIdPath = '/mdm/procedure/{id}';

  /**
   * Obtener un Medical Procedure por ID.
   *
   * Devuelve un objeto Medical Procedure por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProcedureById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProcedureById$Response(params: GetProcedureById$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalProcedure>> {
    return getProcedureById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Medical Procedure por ID.
   *
   * Devuelve un objeto Medical Procedure por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProcedureById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProcedureById(params: GetProcedureById$Params, context?: HttpContext): Observable<MedicalProcedure> {
    return this.getProcedureById$Response(params, context).pipe(
      map((r: StrictHttpResponse<MedicalProcedure>): MedicalProcedure => r.body)
    );
  }

  /** Path part for operation `updateProcedure()` */
  static readonly UpdateProcedurePath = '/mdm/procedure/{id}';

  /**
   * Actualizar un Medical Procedure por ID.
   *
   * Actualiza un Medical Procedure existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProcedure()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProcedure$Response(params: UpdateProcedure$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalProcedure>> {
    return updateProcedure(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Medical Procedure por ID.
   *
   * Actualiza un Medical Procedure existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProcedure$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProcedure(params: UpdateProcedure$Params, context?: HttpContext): Observable<MedicalProcedure> {
    return this.updateProcedure$Response(params, context).pipe(
      map((r: StrictHttpResponse<MedicalProcedure>): MedicalProcedure => r.body)
    );
  }

  /** Path part for operation `deleteProcedure()` */
  static readonly DeleteProcedurePath = '/mdm/procedure/{id}';

  /**
   * Medical Procedure a eliminar por ID.
   *
   * Elimina un Medical Procedure existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProcedure()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProcedure$Response(params: DeleteProcedure$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProcedure(this.http, this.rootUrl, params, context);
  }

  /**
   * Medical Procedure a eliminar por ID.
   *
   * Elimina un Medical Procedure existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProcedure$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProcedure(params: DeleteProcedure$Params, context?: HttpContext): Observable<void> {
    return this.deleteProcedure$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedProcedures()` */
  static readonly GetPaginatedProceduresPath = '/mdm/procedure';

  /**
   * Obtiene una lista paginada de Medical Procedure.
   *
   * Devuelve una lista paginada de Medical Procedure
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedProcedures()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProcedures$Response(params?: GetPaginatedProcedures$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoMedicalProcedure>> {
    return getPaginatedProcedures(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Medical Procedure.
   *
   * Devuelve una lista paginada de Medical Procedure
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedProcedures$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProcedures(params?: GetPaginatedProcedures$Params, context?: HttpContext): Observable<PageResponseDtoMedicalProcedure> {
    return this.getPaginatedProcedures$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoMedicalProcedure>): PageResponseDtoMedicalProcedure => r.body)
    );
  }

  /** Path part for operation `createProcedure()` */
  static readonly CreateProcedurePath = '/mdm/procedure';

  /**
   * Crear un Medical Procedure.
   *
   * Crea un nuevo Medical Procedure usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProcedure()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProcedure$Response(params: CreateProcedure$Params, context?: HttpContext): Observable<StrictHttpResponse<MedicalProcedure>> {
    return createProcedure(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Medical Procedure.
   *
   * Crea un nuevo Medical Procedure usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProcedure$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProcedure(params: CreateProcedure$Params, context?: HttpContext): Observable<MedicalProcedure> {
    return this.createProcedure$Response(params, context).pipe(
      map((r: StrictHttpResponse<MedicalProcedure>): MedicalProcedure => r.body)
    );
  }

  /** Path part for operation `getAllProcedures()` */
  static readonly GetAllProceduresPath = '/mdm/procedure/all';

  /**
   * Obtiene todos los Medical Procedure.
   *
   * Devuelve la lista completa de Medical Procedure
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllProcedures()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProcedures$Response(params?: GetAllProcedures$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MedicalProcedure>>> {
    return getAllProcedures(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Medical Procedure.
   *
   * Devuelve la lista completa de Medical Procedure
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllProcedures$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProcedures(params?: GetAllProcedures$Params, context?: HttpContext): Observable<Array<MedicalProcedure>> {
    return this.getAllProcedures$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MedicalProcedure>>): Array<MedicalProcedure> => r.body)
    );
  }

}
