/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createMedication } from '../fn/medication/create-medication';
import { CreateMedication$Params } from '../fn/medication/create-medication';
import { deleteMedication } from '../fn/medication/delete-medication';
import { DeleteMedication$Params } from '../fn/medication/delete-medication';
import { getAllMedications } from '../fn/medication/get-all-medications';
import { GetAllMedications$Params } from '../fn/medication/get-all-medications';
import { getMedicationById } from '../fn/medication/get-medication-by-id';
import { GetMedicationById$Params } from '../fn/medication/get-medication-by-id';
import { getPaginatedMedications } from '../fn/medication/get-paginated-medications';
import { GetPaginatedMedications$Params } from '../fn/medication/get-paginated-medications';
import { Medication } from '../models/medication';
import { PageResponseDtoMedication } from '../models/page-response-dto-medication';
import { updateMedication } from '../fn/medication/update-medication';
import { UpdateMedication$Params } from '../fn/medication/update-medication';


/**
 * REST API para gestionar el catálogo de medicamentos (Vademécum - MDM).
 */
@Injectable({ providedIn: 'root' })
export class MedicationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMedicationById()` */
  static readonly GetMedicationByIdPath = '/mdm/medication/{id}';

  /**
   * Obtener un Medication por ID.
   *
   * Devuelve un objeto Medication por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMedicationById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMedicationById$Response(params: GetMedicationById$Params, context?: HttpContext): Observable<StrictHttpResponse<Medication>> {
    return getMedicationById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Medication por ID.
   *
   * Devuelve un objeto Medication por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMedicationById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMedicationById(params: GetMedicationById$Params, context?: HttpContext): Observable<Medication> {
    return this.getMedicationById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Medication>): Medication => r.body)
    );
  }

  /** Path part for operation `updateMedication()` */
  static readonly UpdateMedicationPath = '/mdm/medication/{id}';

  /**
   * Actualizar un Medication por ID.
   *
   * Actualiza un Medication existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMedication()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMedication$Response(params: UpdateMedication$Params, context?: HttpContext): Observable<StrictHttpResponse<Medication>> {
    return updateMedication(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Medication por ID.
   *
   * Actualiza un Medication existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMedication$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMedication(params: UpdateMedication$Params, context?: HttpContext): Observable<Medication> {
    return this.updateMedication$Response(params, context).pipe(
      map((r: StrictHttpResponse<Medication>): Medication => r.body)
    );
  }

  /** Path part for operation `deleteMedication()` */
  static readonly DeleteMedicationPath = '/mdm/medication/{id}';

  /**
   * Medication a eliminar por ID.
   *
   * Elimina un Medication existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteMedication()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMedication$Response(params: DeleteMedication$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteMedication(this.http, this.rootUrl, params, context);
  }

  /**
   * Medication a eliminar por ID.
   *
   * Elimina un Medication existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteMedication$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteMedication(params: DeleteMedication$Params, context?: HttpContext): Observable<void> {
    return this.deleteMedication$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedMedications()` */
  static readonly GetPaginatedMedicationsPath = '/mdm/medication';

  /**
   * Obtiene una lista paginada de Medication.
   *
   * Devuelve una lista paginada de Medication
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedMedications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedMedications$Response(params?: GetPaginatedMedications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoMedication>> {
    return getPaginatedMedications(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Medication.
   *
   * Devuelve una lista paginada de Medication
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedMedications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedMedications(params?: GetPaginatedMedications$Params, context?: HttpContext): Observable<PageResponseDtoMedication> {
    return this.getPaginatedMedications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoMedication>): PageResponseDtoMedication => r.body)
    );
  }

  /** Path part for operation `createMedication()` */
  static readonly CreateMedicationPath = '/mdm/medication';

  /**
   * Crear un Medication.
   *
   * Crea un nuevo Medication usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createMedication()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMedication$Response(params: CreateMedication$Params, context?: HttpContext): Observable<StrictHttpResponse<Medication>> {
    return createMedication(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Medication.
   *
   * Crea un nuevo Medication usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createMedication$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMedication(params: CreateMedication$Params, context?: HttpContext): Observable<Medication> {
    return this.createMedication$Response(params, context).pipe(
      map((r: StrictHttpResponse<Medication>): Medication => r.body)
    );
  }

  /** Path part for operation `getAllMedications()` */
  static readonly GetAllMedicationsPath = '/mdm/medication/all';

  /**
   * Obtiene todos los Medication.
   *
   * Devuelve la lista completa de Medication
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllMedications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllMedications$Response(params?: GetAllMedications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Medication>>> {
    return getAllMedications(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Medication.
   *
   * Devuelve la lista completa de Medication
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllMedications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllMedications(params?: GetAllMedications$Params, context?: HttpContext): Observable<Array<Medication>> {
    return this.getAllMedications$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Medication>>): Array<Medication> => r.body)
    );
  }

}
