/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createRole } from '../fn/role/create-role';
import { CreateRole$Params } from '../fn/role/create-role';
import { deleteRole } from '../fn/role/delete-role';
import { DeleteRole$Params } from '../fn/role/delete-role';
import { getAllRoles } from '../fn/role/get-all-roles';
import { GetAllRoles$Params } from '../fn/role/get-all-roles';
import { getPaginatedRoles } from '../fn/role/get-paginated-roles';
import { GetPaginatedRoles$Params } from '../fn/role/get-paginated-roles';
import { getRoleById } from '../fn/role/get-role-by-id';
import { GetRoleById$Params } from '../fn/role/get-role-by-id';
import { PageResponseDtoRole } from '../models/page-response-dto-role';
import { Role } from '../models/role';
import { updateRole } from '../fn/role/update-role';
import { UpdateRole$Params } from '../fn/role/update-role';


/**
 * REST API para gestionar detalles de roles: crear, actualizar, obtener y eliminar.
 */
@Injectable({ providedIn: 'root' })
export class RoleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRoleById()` */
  static readonly GetRoleByIdPath = '/roles/{id}';

  /**
   * Obtener un Role por ID.
   *
   * Devuelve un objeto Role por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRoleById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoleById$Response(params: GetRoleById$Params, context?: HttpContext): Observable<StrictHttpResponse<Role>> {
    return getRoleById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Role por ID.
   *
   * Devuelve un objeto Role por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRoleById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoleById(params: GetRoleById$Params, context?: HttpContext): Observable<Role> {
    return this.getRoleById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Role>): Role => r.body)
    );
  }

  /** Path part for operation `updateRole()` */
  static readonly UpdateRolePath = '/roles/{id}';

  /**
   * Actualizar un Role por ID.
   *
   * Actualiza un Role  existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRole$Response(params: UpdateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<Role>> {
    return updateRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Role por ID.
   *
   * Actualiza un Role  existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRole(params: UpdateRole$Params, context?: HttpContext): Observable<Role> {
    return this.updateRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<Role>): Role => r.body)
    );
  }

  /** Path part for operation `deleteRole()` */
  static readonly DeleteRolePath = '/roles/{id}';

  /**
   * Role a eliminar por ID.
   *
   * Elimina un Role existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRole$Response(params: DeleteRole$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Role a eliminar por ID.
   *
   * Elimina un Role existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRole(params: DeleteRole$Params, context?: HttpContext): Observable<void> {
    return this.deleteRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedRoles()` */
  static readonly GetPaginatedRolesPath = '/roles';

  /**
   * Obtiene una lista paginada de Role.
   *
   * Devuelve una lista paginada de Role
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedRoles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedRoles$Response(params?: GetPaginatedRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoRole>> {
    return getPaginatedRoles(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Role.
   *
   * Devuelve una lista paginada de Role
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedRoles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedRoles(params?: GetPaginatedRoles$Params, context?: HttpContext): Observable<PageResponseDtoRole> {
    return this.getPaginatedRoles$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoRole>): PageResponseDtoRole => r.body)
    );
  }

  /** Path part for operation `createRole()` */
  static readonly CreateRolePath = '/roles';

  /**
   * Crear un Role.
   *
   * Crea un nuevo Role usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRole$Response(params: CreateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<Role>> {
    return createRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Role.
   *
   * Crea un nuevo Role usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRole(params: CreateRole$Params, context?: HttpContext): Observable<Role> {
    return this.createRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<Role>): Role => r.body)
    );
  }

  /** Path part for operation `getAllRoles()` */
  static readonly GetAllRolesPath = '/roles/all';

  /**
   * Obtiene todos los Role.
   *
   * Devuelve la lista completa de Role
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRoles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles$Response(params?: GetAllRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Role>>> {
    return getAllRoles(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Role.
   *
   * Devuelve la lista completa de Role
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRoles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles(params?: GetAllRoles$Params, context?: HttpContext): Observable<Array<Role>> {
    return this.getAllRoles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Role>>): Array<Role> => r.body)
    );
  }

}
