/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createSuperAdmin } from '../fn/tenant-admin-management/create-super-admin';
import { CreateSuperAdmin$Params } from '../fn/tenant-admin-management/create-super-admin';
import { deleteSuperAdmin } from '../fn/tenant-admin-management/delete-super-admin';
import { DeleteSuperAdmin$Params } from '../fn/tenant-admin-management/delete-super-admin';
import { getAllSuperAdmins } from '../fn/tenant-admin-management/get-all-super-admins';
import { GetAllSuperAdmins$Params } from '../fn/tenant-admin-management/get-all-super-admins';
import { getPaginatedSuperAdmins } from '../fn/tenant-admin-management/get-paginated-super-admins';
import { GetPaginatedSuperAdmins$Params } from '../fn/tenant-admin-management/get-paginated-super-admins';
import { getSuperAdminById } from '../fn/tenant-admin-management/get-super-admin-by-id';
import { GetSuperAdminById$Params } from '../fn/tenant-admin-management/get-super-admin-by-id';
import { PageResponseDtoSuperAdmin } from '../models/page-response-dto-super-admin';
import { SuperAdmin } from '../models/super-admin';
import { updateSuperAdmin } from '../fn/tenant-admin-management/update-super-admin';
import { UpdateSuperAdmin$Params } from '../fn/tenant-admin-management/update-super-admin';


/**
 * REST API para gestionar detalles del Super Admin: crear, actualizar, obtener y eliminar.
 */
@Injectable({ providedIn: 'root' })
export class SuperAdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getSuperAdminById()` */
  static readonly GetSuperAdminByIdPath = '/super-admin/{id}';

  /**
   * Obtener un SuperAdmin por ID.
   *
   * Devuelve un objeto SuperAdmin por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSuperAdminById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSuperAdminById$Response(params: GetSuperAdminById$Params, context?: HttpContext): Observable<StrictHttpResponse<SuperAdmin>> {
    return getSuperAdminById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un SuperAdmin por ID.
   *
   * Devuelve un objeto SuperAdmin por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSuperAdminById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSuperAdminById(params: GetSuperAdminById$Params, context?: HttpContext): Observable<SuperAdmin> {
    return this.getSuperAdminById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuperAdmin>): SuperAdmin => r.body)
    );
  }

  /** Path part for operation `updateSuperAdmin()` */
  static readonly UpdateSuperAdminPath = '/super-admin/{id}';

  /**
   * Actualizar un SuperAdmin por ID.
   *
   * Actualiza un SuperAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSuperAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSuperAdmin$Response(params: UpdateSuperAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<SuperAdmin>> {
    return updateSuperAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un SuperAdmin por ID.
   *
   * Actualiza un SuperAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSuperAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSuperAdmin(params: UpdateSuperAdmin$Params, context?: HttpContext): Observable<SuperAdmin> {
    return this.updateSuperAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuperAdmin>): SuperAdmin => r.body)
    );
  }

  /** Path part for operation `deleteSuperAdmin()` */
  static readonly DeleteSuperAdminPath = '/super-admin/{id}';

  /**
   * SuperAdmin a eliminar por ID.
   *
   * Elimina un SuperAdmin existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSuperAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSuperAdmin$Response(params: DeleteSuperAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteSuperAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * SuperAdmin a eliminar por ID.
   *
   * Elimina un SuperAdmin existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSuperAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSuperAdmin(params: DeleteSuperAdmin$Params, context?: HttpContext): Observable<void> {
    return this.deleteSuperAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedSuperAdmins()` */
  static readonly GetPaginatedSuperAdminsPath = '/super-admin/';

  /**
   * Obtiene una lista paginada de SuperAdmin.
   *
   * Devuelve una lista paginada de SuperAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedSuperAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedSuperAdmins$Response(params?: GetPaginatedSuperAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoSuperAdmin>> {
    return getPaginatedSuperAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de SuperAdmin.
   *
   * Devuelve una lista paginada de SuperAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedSuperAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedSuperAdmins(params?: GetPaginatedSuperAdmins$Params, context?: HttpContext): Observable<PageResponseDtoSuperAdmin> {
    return this.getPaginatedSuperAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoSuperAdmin>): PageResponseDtoSuperAdmin => r.body)
    );
  }

  /** Path part for operation `createSuperAdmin()` */
  static readonly CreateSuperAdminPath = '/super-admin/';

  /**
   * Crear un SuperAdmin.
   *
   * Crea un nuevo SuperAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSuperAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSuperAdmin$Response(params: CreateSuperAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<SuperAdmin>> {
    return createSuperAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un SuperAdmin.
   *
   * Crea un nuevo SuperAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSuperAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSuperAdmin(params: CreateSuperAdmin$Params, context?: HttpContext): Observable<SuperAdmin> {
    return this.createSuperAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuperAdmin>): SuperAdmin => r.body)
    );
  }

  /** Path part for operation `getAllSuperAdmins()` */
  static readonly GetAllSuperAdminsPath = '/super-admin/all';

  /**
   * Obtiene todos los SuperAdmin.
   *
   * Devuelve la lista completa de SuperAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllSuperAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSuperAdmins$Response(params?: GetAllSuperAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SuperAdmin>>> {
    return getAllSuperAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los SuperAdmin.
   *
   * Devuelve la lista completa de SuperAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllSuperAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSuperAdmins(params?: GetAllSuperAdmins$Params, context?: HttpContext): Observable<Array<SuperAdmin>> {
    return this.getAllSuperAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SuperAdmin>>): Array<SuperAdmin> => r.body)
    );
  }

}
