/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTenant } from '../fn/tenant/create-tenant';
import { CreateTenant$Params } from '../fn/tenant/create-tenant';
import { deleteTenant } from '../fn/tenant/delete-tenant';
import { DeleteTenant$Params } from '../fn/tenant/delete-tenant';
import { disable } from '../fn/tenant/disable';
import { Disable$Params } from '../fn/tenant/disable';
import { enable } from '../fn/tenant/enable';
import { Enable$Params } from '../fn/tenant/enable';
import { getAllTenants } from '../fn/tenant/get-all-tenants';
import { GetAllTenants$Params } from '../fn/tenant/get-all-tenants';
import { getPaginatedTenants } from '../fn/tenant/get-paginated-tenants';
import { GetPaginatedTenants$Params } from '../fn/tenant/get-paginated-tenants';
import { getPublicAllTenants } from '../fn/tenant/get-public-all-tenants';
import { GetPublicAllTenants$Params } from '../fn/tenant/get-public-all-tenants';
import { getTenantById } from '../fn/tenant/get-tenant-by-id';
import { GetTenantById$Params } from '../fn/tenant/get-tenant-by-id';
import { PageResponseDtoTenant } from '../models/page-response-dto-tenant';
import { Tenant } from '../models/tenant';
import { updateTenant } from '../fn/tenant/update-tenant';
import { UpdateTenant$Params } from '../fn/tenant/update-tenant';


/**
 * REST API para gestionar detalles de tenants: crear, actualizar, obtener y eliminar.
 */
@Injectable({ providedIn: 'root' })
export class TenantService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTenantById()` */
  static readonly GetTenantByIdPath = '/super-admin/tenants/{id}';

  /**
   * Obtener un Tenant por ID.
   *
   * Devuelve un objeto Tenant por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTenantById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantById$Response(params: GetTenantById$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
    return getTenantById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un Tenant por ID.
   *
   * Devuelve un objeto Tenant por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTenantById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantById(params: GetTenantById$Params, context?: HttpContext): Observable<Tenant> {
    return this.getTenantById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Tenant>): Tenant => r.body)
    );
  }

  /** Path part for operation `updateTenant()` */
  static readonly UpdateTenantPath = '/super-admin/tenants/{id}';

  /**
   * Actualizar un Tenant por ID.
   *
   * Actualiza un Tenant  existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTenant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenant$Response(params: UpdateTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
    return updateTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un Tenant por ID.
   *
   * Actualiza un Tenant  existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTenant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenant(params: UpdateTenant$Params, context?: HttpContext): Observable<Tenant> {
    return this.updateTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<Tenant>): Tenant => r.body)
    );
  }

  /** Path part for operation `deleteTenant()` */
  static readonly DeleteTenantPath = '/super-admin/tenants/{id}';

  /**
   * Tenant a eliminar por ID.
   *
   * Elimina un Tenant existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenant$Response(params: DeleteTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * Tenant a eliminar por ID.
   *
   * Elimina un Tenant existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenant(params: DeleteTenant$Params, context?: HttpContext): Observable<void> {
    return this.deleteTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedTenants()` */
  static readonly GetPaginatedTenantsPath = '/super-admin/tenants';

  /**
   * Obtiene una lista paginada de Tenant.
   *
   * Devuelve una lista paginada de Tenant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedTenants()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenants$Response(params?: GetPaginatedTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoTenant>> {
    return getPaginatedTenants(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de Tenant.
   *
   * Devuelve una lista paginada de Tenant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedTenants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenants(params?: GetPaginatedTenants$Params, context?: HttpContext): Observable<PageResponseDtoTenant> {
    return this.getPaginatedTenants$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoTenant>): PageResponseDtoTenant => r.body)
    );
  }

  /** Path part for operation `createTenant()` */
  static readonly CreateTenantPath = '/super-admin/tenants';

  /**
   * Crear un Tenant.
   *
   * Crea un nuevo Tenant usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTenant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenant$Response(params: CreateTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
    return createTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un Tenant.
   *
   * Crea un nuevo Tenant usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTenant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenant(params: CreateTenant$Params, context?: HttpContext): Observable<Tenant> {
    return this.createTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<Tenant>): Tenant => r.body)
    );
  }

  /** Path part for operation `enable()` */
  static readonly EnablePath = '/super-admin/tenants/{id}/enable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enable()` instead.
   *
   * This method doesn't expect any request body.
   */
  enable$Response(params: Enable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return enable(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  enable(params: Enable$Params, context?: HttpContext): Observable<void> {
    return this.enable$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `disable()` */
  static readonly DisablePath = '/super-admin/tenants/{id}/disable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `disable()` instead.
   *
   * This method doesn't expect any request body.
   */
  disable$Response(params: Disable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return disable(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `disable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  disable(params: Disable$Params, context?: HttpContext): Observable<void> {
    return this.disable$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPublicAllTenants()` */
  static readonly GetPublicAllTenantsPath = '/tenants';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPublicAllTenants()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublicAllTenants$Response(params?: GetPublicAllTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Tenant>>> {
    return getPublicAllTenants(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPublicAllTenants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublicAllTenants(params?: GetPublicAllTenants$Params, context?: HttpContext): Observable<Array<Tenant>> {
    return this.getPublicAllTenants$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Tenant>>): Array<Tenant> => r.body)
    );
  }

  /** Path part for operation `getAllTenants()` */
  static readonly GetAllTenantsPath = '/super-admin/tenants/all';

  /**
   * Obtiene todos los Tenant.
   *
   * Devuelve la lista completa de Tenant
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTenants()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenants$Response(params?: GetAllTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Tenant>>> {
    return getAllTenants(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los Tenant.
   *
   * Devuelve la lista completa de Tenant
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTenants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenants(params?: GetAllTenants$Params, context?: HttpContext): Observable<Array<Tenant>> {
    return this.getAllTenants$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Tenant>>): Array<Tenant> => r.body)
    );
  }

}
