/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTenantAdmin } from '../fn/tenant-admin/create-tenant-admin';
import { CreateTenantAdmin$Params } from '../fn/tenant-admin/create-tenant-admin';
import { deleteTenantAdmin } from '../fn/tenant-admin/delete-tenant-admin';
import { DeleteTenantAdmin$Params } from '../fn/tenant-admin/delete-tenant-admin';
import { getAllTenantAdmins } from '../fn/tenant-admin/get-all-tenant-admins';
import { GetAllTenantAdmins$Params } from '../fn/tenant-admin/get-all-tenant-admins';
import { getPaginatedTenantAdmins } from '../fn/tenant-admin/get-paginated-tenant-admins';
import { GetPaginatedTenantAdmins$Params } from '../fn/tenant-admin/get-paginated-tenant-admins';
import { getTenantAdminById } from '../fn/tenant-admin/get-tenant-admin-by-id';
import { GetTenantAdminById$Params } from '../fn/tenant-admin/get-tenant-admin-by-id';
import { PageResponseDtoTenantAdmin } from '../models/page-response-dto-tenant-admin';
import { resetAdminPassword } from '../fn/tenant-admin/reset-admin-password';
import { ResetAdminPassword$Params } from '../fn/tenant-admin/reset-admin-password';
import { TenantAdmin } from '../models/tenant-admin';
import { updateTenantAdmin } from '../fn/tenant-admin/update-tenant-admin';
import { UpdateTenantAdmin$Params } from '../fn/tenant-admin/update-tenant-admin';


/**
 * REST API para gestionar detalles del tenant admin: crear, actualizar, obtener y eliminar.
 */
@Injectable({ providedIn: 'root' })
export class TenantAdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTenantAdminById()` */
  static readonly GetTenantAdminByIdPath = '/super-admin/tenant-admins/{id}';

  /**
   * Obtener un TenantAdmin por ID.
   *
   * Devuelve un objeto TenantAdmin por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTenantAdminById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantAdminById$Response(params: GetTenantAdminById$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
    return getTenantAdminById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un TenantAdmin por ID.
   *
   * Devuelve un objeto TenantAdmin por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTenantAdminById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantAdminById(params: GetTenantAdminById$Params, context?: HttpContext): Observable<TenantAdmin> {
    return this.getTenantAdminById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantAdmin>): TenantAdmin => r.body)
    );
  }

  /** Path part for operation `updateTenantAdmin()` */
  static readonly UpdateTenantAdminPath = '/super-admin/tenant-admins/{id}';

  /**
   * Actualizar un TenantAdmin por ID.
   *
   * Actualiza un TenantAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTenantAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenantAdmin$Response(params: UpdateTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
    return updateTenantAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un TenantAdmin por ID.
   *
   * Actualiza un TenantAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTenantAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenantAdmin(params: UpdateTenantAdmin$Params, context?: HttpContext): Observable<TenantAdmin> {
    return this.updateTenantAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantAdmin>): TenantAdmin => r.body)
    );
  }

  /** Path part for operation `deleteTenantAdmin()` */
  static readonly DeleteTenantAdminPath = '/super-admin/tenant-admins/{id}';

  /**
   * TenantAdmin a eliminar por ID.
   *
   * Elimina un TenantAdmin existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTenantAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenantAdmin$Response(params: DeleteTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTenantAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * TenantAdmin a eliminar por ID.
   *
   * Elimina un TenantAdmin existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTenantAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenantAdmin(params: DeleteTenantAdmin$Params, context?: HttpContext): Observable<void> {
    return this.deleteTenantAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedTenantAdmins()` */
  static readonly GetPaginatedTenantAdminsPath = '/super-admin/tenant-admins';

  /**
   * Obtiene una lista paginada de TenantAdmin.
   *
   * Devuelve una lista paginada de TenantAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedTenantAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenantAdmins$Response(params?: GetPaginatedTenantAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoTenantAdmin>> {
    return getPaginatedTenantAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de TenantAdmin.
   *
   * Devuelve una lista paginada de TenantAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedTenantAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenantAdmins(params?: GetPaginatedTenantAdmins$Params, context?: HttpContext): Observable<PageResponseDtoTenantAdmin> {
    return this.getPaginatedTenantAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoTenantAdmin>): PageResponseDtoTenantAdmin => r.body)
    );
  }

  /** Path part for operation `createTenantAdmin()` */
  static readonly CreateTenantAdminPath = '/super-admin/tenant-admins';

  /**
   * Crear un TenantAdmin.
   *
   * Crea un nuevo TenantAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTenantAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenantAdmin$Response(params: CreateTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
    return createTenantAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un TenantAdmin.
   *
   * Crea un nuevo TenantAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTenantAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenantAdmin(params: CreateTenantAdmin$Params, context?: HttpContext): Observable<TenantAdmin> {
    return this.createTenantAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantAdmin>): TenantAdmin => r.body)
    );
  }

  /** Path part for operation `resetAdminPassword()` */
  static readonly ResetAdminPasswordPath = '/super-admin/tenant-admins/{id}/reset-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetAdminPassword()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetAdminPassword$Response(params: ResetAdminPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return resetAdminPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetAdminPassword$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetAdminPassword(params: ResetAdminPassword$Params, context?: HttpContext): Observable<void> {
    return this.resetAdminPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllTenantAdmins()` */
  static readonly GetAllTenantAdminsPath = '/super-admin/tenant-admins/all';

  /**
   * Obtiene todos los TenantAdmin.
   *
   * Devuelve la lista completa de TenantAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTenantAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenantAdmins$Response(params?: GetAllTenantAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TenantAdmin>>> {
    return getAllTenantAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los TenantAdmin.
   *
   * Devuelve la lista completa de TenantAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTenantAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenantAdmins(params?: GetAllTenantAdmins$Params, context?: HttpContext): Observable<Array<TenantAdmin>> {
    return this.getAllTenantAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TenantAdmin>>): Array<TenantAdmin> => r.body)
    );
  }

}
