/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createSuperAdmin } from '../fn/tenant-admin-management/create-super-admin';
import { CreateSuperAdmin$Params } from '../fn/tenant-admin-management/create-super-admin';
import { createTenantAdmin } from '../fn/tenant-admin/create-tenant-admin';
import { CreateTenantAdmin$Params } from '../fn/tenant-admin/create-tenant-admin';
import { deleteSuperAdmin } from '../fn/tenant-admin-management/delete-super-admin';
import { DeleteSuperAdmin$Params } from '../fn/tenant-admin-management/delete-super-admin';
import { deleteTenantAdmin } from '../fn/tenant-admin/delete-tenant-admin';
import { DeleteTenantAdmin$Params } from '../fn/tenant-admin/delete-tenant-admin';
import { getAllSuperAdmins } from '../fn/tenant-admin-management/get-all-super-admins';
import { GetAllSuperAdmins$Params } from '../fn/tenant-admin-management/get-all-super-admins';
import { getAllTenantAdmins } from '../fn/tenant-admin/get-all-tenant-admins';
import { GetAllTenantAdmins$Params } from '../fn/tenant-admin/get-all-tenant-admins';
import { getPaginatedSuperAdmins } from '../fn/tenant-admin-management/get-paginated-super-admins';
import { GetPaginatedSuperAdmins$Params } from '../fn/tenant-admin-management/get-paginated-super-admins';
import { getPaginatedTenantAdmins } from '../fn/tenant-admin/get-paginated-tenant-admins';
import { GetPaginatedTenantAdmins$Params } from '../fn/tenant-admin/get-paginated-tenant-admins';
import { getSuperAdminById } from '../fn/tenant-admin-management/get-super-admin-by-id';
import { GetSuperAdminById$Params } from '../fn/tenant-admin-management/get-super-admin-by-id';
import { getTenantAdminById } from '../fn/tenant-admin/get-tenant-admin-by-id';
import { GetTenantAdminById$Params } from '../fn/tenant-admin/get-tenant-admin-by-id';
import { PageResponseDtoSuperAdmin } from '../models/page-response-dto-super-admin';
import { PageResponseDtoTenantAdmin } from '../models/page-response-dto-tenant-admin';
import { resetAdminPassword } from '../fn/tenant-admin/reset-admin-password';
import { ResetAdminPassword$Params } from '../fn/tenant-admin/reset-admin-password';
import { SuperAdmin } from '../models/super-admin';
import { TenantAdmin } from '../models/tenant-admin';
import { updateSuperAdmin } from '../fn/tenant-admin-management/update-super-admin';
import { UpdateSuperAdmin$Params } from '../fn/tenant-admin-management/update-super-admin';
import { updateTenantAdmin } from '../fn/tenant-admin/update-tenant-admin';
import { UpdateTenantAdmin$Params } from '../fn/tenant-admin/update-tenant-admin';


/**
 * Gestión de administradores de tenants
 */
@Injectable({ providedIn: 'root' })
export class TenantAdminManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getSuperAdminById()` */
  static readonly GetSuperAdminByIdPath = '/super-admin/{id}';

  /**
   * Obtener un SuperAdmin por ID.
   *
   * Devuelve un objeto SuperAdmin por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSuperAdminById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSuperAdminById$Response(params: GetSuperAdminById$Params, context?: HttpContext): Observable<StrictHttpResponse<SuperAdmin>> {
    return getSuperAdminById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un SuperAdmin por ID.
   *
   * Devuelve un objeto SuperAdmin por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSuperAdminById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSuperAdminById(params: GetSuperAdminById$Params, context?: HttpContext): Observable<SuperAdmin> {
    return this.getSuperAdminById$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuperAdmin>): SuperAdmin => r.body)
    );
  }

  /** Path part for operation `updateSuperAdmin()` */
  static readonly UpdateSuperAdminPath = '/super-admin/{id}';

  /**
   * Actualizar un SuperAdmin por ID.
   *
   * Actualiza un SuperAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSuperAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSuperAdmin$Response(params: UpdateSuperAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<SuperAdmin>> {
    return updateSuperAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un SuperAdmin por ID.
   *
   * Actualiza un SuperAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSuperAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSuperAdmin(params: UpdateSuperAdmin$Params, context?: HttpContext): Observable<SuperAdmin> {
    return this.updateSuperAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuperAdmin>): SuperAdmin => r.body)
    );
  }

  /** Path part for operation `deleteSuperAdmin()` */
  static readonly DeleteSuperAdminPath = '/super-admin/{id}';

  /**
   * SuperAdmin a eliminar por ID.
   *
   * Elimina un SuperAdmin existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteSuperAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSuperAdmin$Response(params: DeleteSuperAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteSuperAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * SuperAdmin a eliminar por ID.
   *
   * Elimina un SuperAdmin existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteSuperAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteSuperAdmin(params: DeleteSuperAdmin$Params, context?: HttpContext): Observable<void> {
    return this.deleteSuperAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getTenantAdminById()` */
  static readonly GetTenantAdminByIdPath = '/super-admin/tenant-admins/{id}';

  /**
   * Obtener un TenantAdmin por ID.
   *
   * Devuelve un objeto TenantAdmin por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTenantAdminById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantAdminById$Response(params: GetTenantAdminById$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
    return getTenantAdminById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un TenantAdmin por ID.
   *
   * Devuelve un objeto TenantAdmin por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTenantAdminById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantAdminById(params: GetTenantAdminById$Params, context?: HttpContext): Observable<TenantAdmin> {
    return this.getTenantAdminById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantAdmin>): TenantAdmin => r.body)
    );
  }

  /** Path part for operation `updateTenantAdmin()` */
  static readonly UpdateTenantAdminPath = '/super-admin/tenant-admins/{id}';

  /**
   * Actualizar un TenantAdmin por ID.
   *
   * Actualiza un TenantAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTenantAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenantAdmin$Response(params: UpdateTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
    return updateTenantAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un TenantAdmin por ID.
   *
   * Actualiza un TenantAdmin  existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTenantAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenantAdmin(params: UpdateTenantAdmin$Params, context?: HttpContext): Observable<TenantAdmin> {
    return this.updateTenantAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantAdmin>): TenantAdmin => r.body)
    );
  }

  /** Path part for operation `deleteTenantAdmin()` */
  static readonly DeleteTenantAdminPath = '/super-admin/tenant-admins/{id}';

  /**
   * TenantAdmin a eliminar por ID.
   *
   * Elimina un TenantAdmin existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTenantAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenantAdmin$Response(params: DeleteTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTenantAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * TenantAdmin a eliminar por ID.
   *
   * Elimina un TenantAdmin existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTenantAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenantAdmin(params: DeleteTenantAdmin$Params, context?: HttpContext): Observable<void> {
    return this.deleteTenantAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedTenantAdmins()` */
  static readonly GetPaginatedTenantAdminsPath = '/super-admin/tenant-admins';

  /**
   * Obtiene una lista paginada de TenantAdmin.
   *
   * Devuelve una lista paginada de TenantAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedTenantAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenantAdmins$Response(params?: GetPaginatedTenantAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoTenantAdmin>> {
    return getPaginatedTenantAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de TenantAdmin.
   *
   * Devuelve una lista paginada de TenantAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedTenantAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenantAdmins(params?: GetPaginatedTenantAdmins$Params, context?: HttpContext): Observable<PageResponseDtoTenantAdmin> {
    return this.getPaginatedTenantAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoTenantAdmin>): PageResponseDtoTenantAdmin => r.body)
    );
  }

  /** Path part for operation `createTenantAdmin()` */
  static readonly CreateTenantAdminPath = '/super-admin/tenant-admins';

  /**
   * Crear un TenantAdmin.
   *
   * Crea un nuevo TenantAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTenantAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenantAdmin$Response(params: CreateTenantAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantAdmin>> {
    return createTenantAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un TenantAdmin.
   *
   * Crea un nuevo TenantAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTenantAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenantAdmin(params: CreateTenantAdmin$Params, context?: HttpContext): Observable<TenantAdmin> {
    return this.createTenantAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantAdmin>): TenantAdmin => r.body)
    );
  }

  /** Path part for operation `getPaginatedSuperAdmins()` */
  static readonly GetPaginatedSuperAdminsPath = '/super-admin/';

  /**
   * Obtiene una lista paginada de SuperAdmin.
   *
   * Devuelve una lista paginada de SuperAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedSuperAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedSuperAdmins$Response(params?: GetPaginatedSuperAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoSuperAdmin>> {
    return getPaginatedSuperAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de SuperAdmin.
   *
   * Devuelve una lista paginada de SuperAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedSuperAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedSuperAdmins(params?: GetPaginatedSuperAdmins$Params, context?: HttpContext): Observable<PageResponseDtoSuperAdmin> {
    return this.getPaginatedSuperAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoSuperAdmin>): PageResponseDtoSuperAdmin => r.body)
    );
  }

  /** Path part for operation `createSuperAdmin()` */
  static readonly CreateSuperAdminPath = '/super-admin/';

  /**
   * Crear un SuperAdmin.
   *
   * Crea un nuevo SuperAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSuperAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSuperAdmin$Response(params: CreateSuperAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<SuperAdmin>> {
    return createSuperAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un SuperAdmin.
   *
   * Crea un nuevo SuperAdmin usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSuperAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSuperAdmin(params: CreateSuperAdmin$Params, context?: HttpContext): Observable<SuperAdmin> {
    return this.createSuperAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<SuperAdmin>): SuperAdmin => r.body)
    );
  }

  /** Path part for operation `resetAdminPassword()` */
  static readonly ResetAdminPasswordPath = '/super-admin/tenant-admins/{id}/reset-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetAdminPassword()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetAdminPassword$Response(params: ResetAdminPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return resetAdminPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetAdminPassword$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetAdminPassword(params: ResetAdminPassword$Params, context?: HttpContext): Observable<void> {
    return this.resetAdminPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllTenantAdmins()` */
  static readonly GetAllTenantAdminsPath = '/super-admin/tenant-admins/all';

  /**
   * Obtiene todos los TenantAdmin.
   *
   * Devuelve la lista completa de TenantAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTenantAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenantAdmins$Response(params?: GetAllTenantAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TenantAdmin>>> {
    return getAllTenantAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los TenantAdmin.
   *
   * Devuelve la lista completa de TenantAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTenantAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenantAdmins(params?: GetAllTenantAdmins$Params, context?: HttpContext): Observable<Array<TenantAdmin>> {
    return this.getAllTenantAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TenantAdmin>>): Array<TenantAdmin> => r.body)
    );
  }

  /** Path part for operation `getAllSuperAdmins()` */
  static readonly GetAllSuperAdminsPath = '/super-admin/all';

  /**
   * Obtiene todos los SuperAdmin.
   *
   * Devuelve la lista completa de SuperAdmin
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllSuperAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSuperAdmins$Response(params?: GetAllSuperAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SuperAdmin>>> {
    return getAllSuperAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los SuperAdmin.
   *
   * Devuelve la lista completa de SuperAdmin
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllSuperAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllSuperAdmins(params?: GetAllSuperAdmins$Params, context?: HttpContext): Observable<Array<SuperAdmin>> {
    return this.getAllSuperAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SuperAdmin>>): Array<SuperAdmin> => r.body)
    );
  }

}
