/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getTenant1 } from '../fn/tenant-controller/get-tenant-1';
import { GetTenant1$Params } from '../fn/tenant-controller/get-tenant-1';
import { getTenants } from '../fn/tenant-controller/get-tenants';
import { GetTenants$Params } from '../fn/tenant-controller/get-tenants';
import { Tenant } from '../models/tenant';

@Injectable({ providedIn: 'root' })
export class TenantControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTenants()` */
  static readonly GetTenantsPath = '/tenants';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTenants()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenants$Response(params?: GetTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Tenant>>> {
    return getTenants(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTenants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenants(params?: GetTenants$Params, context?: HttpContext): Observable<Array<Tenant>> {
    return this.getTenants$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Tenant>>): Array<Tenant> => r.body)
    );
  }

  /** Path part for operation `getTenant1()` */
  static readonly GetTenant1Path = '/tenants/{code}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTenant1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenant1$Response(params: GetTenant1$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
    return getTenant1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTenant1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenant1(params: GetTenant1$Params, context?: HttpContext): Observable<Tenant> {
    return this.getTenant1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Tenant>): Tenant => r.body)
    );
  }

}
