/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTenant } from '../fn/tenant-management-controller/create-tenant';
import { CreateTenant$Params } from '../fn/tenant-management-controller/create-tenant';
import { disable } from '../fn/tenant-management-controller/disable';
import { Disable$Params } from '../fn/tenant-management-controller/disable';
import { enable } from '../fn/tenant-management-controller/enable';
import { Enable$Params } from '../fn/tenant-management-controller/enable';
import { getTenant } from '../fn/tenant-management-controller/get-tenant';
import { GetTenant$Params } from '../fn/tenant-management-controller/get-tenant';
import { listTenants } from '../fn/tenant-management-controller/list-tenants';
import { ListTenants$Params } from '../fn/tenant-management-controller/list-tenants';
import { PageTenantResponse } from '../models/page-tenant-response';
import { resetAdminPassword } from '../fn/tenant-management-controller/reset-admin-password';
import { ResetAdminPassword$Params } from '../fn/tenant-management-controller/reset-admin-password';
import { softDelete } from '../fn/tenant-management-controller/soft-delete';
import { SoftDelete$Params } from '../fn/tenant-management-controller/soft-delete';
import { TenantResponse } from '../models/tenant-response';
import { updateTenant } from '../fn/tenant-management-controller/update-tenant';
import { UpdateTenant$Params } from '../fn/tenant-management-controller/update-tenant';

@Injectable({ providedIn: 'root' })
export class TenantManagementControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTenant()` */
  static readonly GetTenantPath = '/super-admin/tenants/{id}';

  /**
   * Obtener información de un tenant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenant$Response(params: GetTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantResponse>> {
    return getTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener información de un tenant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenant(params: GetTenant$Params, context?: HttpContext): Observable<TenantResponse> {
    return this.getTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantResponse>): TenantResponse => r.body)
    );
  }

  /** Path part for operation `updateTenant()` */
  static readonly UpdateTenantPath = '/super-admin/tenants/{id}';

  /**
   * Actualizar tenant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTenant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenant$Response(params: UpdateTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantResponse>> {
    return updateTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar tenant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTenant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenant(params: UpdateTenant$Params, context?: HttpContext): Observable<TenantResponse> {
    return this.updateTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantResponse>): TenantResponse => r.body)
    );
  }

  /** Path part for operation `softDelete()` */
  static readonly SoftDeletePath = '/super-admin/tenants/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `softDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  softDelete$Response(params: SoftDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return softDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `softDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  softDelete(params: SoftDelete$Params, context?: HttpContext): Observable<void> {
    return this.softDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listTenants()` */
  static readonly ListTenantsPath = '/super-admin/tenants';

  /**
   * Listar tenants (paged).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listTenants()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTenants$Response(params: ListTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<PageTenantResponse>> {
    return listTenants(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar tenants (paged).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listTenants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listTenants(params: ListTenants$Params, context?: HttpContext): Observable<PageTenantResponse> {
    return this.listTenants$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageTenantResponse>): PageTenantResponse => r.body)
    );
  }

  /** Path part for operation `createTenant()` */
  static readonly CreateTenantPath = '/super-admin/tenants';

  /**
   * Crear tenant + tenant admin (solo SUPER_ADMIN).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTenant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenant$Response(params: CreateTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantResponse>> {
    return createTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear tenant + tenant admin (solo SUPER_ADMIN).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTenant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenant(params: CreateTenant$Params, context?: HttpContext): Observable<TenantResponse> {
    return this.createTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantResponse>): TenantResponse => r.body)
    );
  }

  /** Path part for operation `resetAdminPassword()` */
  static readonly ResetAdminPasswordPath = '/super-admin/tenants/{id}/admin/reset-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetAdminPassword()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetAdminPassword$Response(params: ResetAdminPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return resetAdminPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetAdminPassword$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resetAdminPassword(params: ResetAdminPassword$Params, context?: HttpContext): Observable<void> {
    return this.resetAdminPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `enable()` */
  static readonly EnablePath = '/super-admin/tenants/{id}/enable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enable()` instead.
   *
   * This method doesn't expect any request body.
   */
  enable$Response(params: Enable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return enable(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  enable(params: Enable$Params, context?: HttpContext): Observable<void> {
    return this.enable$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `disable()` */
  static readonly DisablePath = '/super-admin/tenants/{id}/disable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `disable()` instead.
   *
   * This method doesn't expect any request body.
   */
  disable$Response(params: Disable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return disable(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `disable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  disable(params: Disable$Params, context?: HttpContext): Observable<void> {
    return this.disable$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
