/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTenantConfig } from '../fn/tenant-config/create-tenant-config';
import { CreateTenantConfig$Params } from '../fn/tenant-config/create-tenant-config';
import { deleteTenantConfig } from '../fn/tenant-config/delete-tenant-config';
import { DeleteTenantConfig$Params } from '../fn/tenant-config/delete-tenant-config';
import { getAllTenantConfigs } from '../fn/tenant-config/get-all-tenant-configs';
import { GetAllTenantConfigs$Params } from '../fn/tenant-config/get-all-tenant-configs';
import { getPaginatedTenantConfigs } from '../fn/tenant-config/get-paginated-tenant-configs';
import { GetPaginatedTenantConfigs$Params } from '../fn/tenant-config/get-paginated-tenant-configs';
import { getTenantConfigById } from '../fn/tenant-config/get-tenant-config-by-id';
import { GetTenantConfigById$Params } from '../fn/tenant-config/get-tenant-config-by-id';
import { PageResponseDtoTenantConfig } from '../models/page-response-dto-tenant-config';
import { TenantConfig } from '../models/tenant-config';
import { updateTenantConfig } from '../fn/tenant-config/update-tenant-config';
import { UpdateTenantConfig$Params } from '../fn/tenant-config/update-tenant-config';


/**
 * REST API para gestionar detalles de tenantConfigs: crear, actualizar, obtener y eliminar.
 */
@Injectable({ providedIn: 'root' })
export class TenantConfigService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTenantConfigById()` */
  static readonly GetTenantConfigByIdPath = '/tenantConfigs/{id}';

  /**
   * Obtener un TenantConfig por ID.
   *
   * Devuelve un objeto TenantConfig por ID especificado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTenantConfigById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantConfigById$Response(params: GetTenantConfigById$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantConfig>> {
    return getTenantConfigById(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener un TenantConfig por ID.
   *
   * Devuelve un objeto TenantConfig por ID especificado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTenantConfigById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTenantConfigById(params: GetTenantConfigById$Params, context?: HttpContext): Observable<TenantConfig> {
    return this.getTenantConfigById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantConfig>): TenantConfig => r.body)
    );
  }

  /** Path part for operation `updateTenantConfig()` */
  static readonly UpdateTenantConfigPath = '/tenantConfigs/{id}';

  /**
   * Actualizar un TenantConfig por ID.
   *
   * Actualiza un TenantConfig  existente usando su ID y los datos proporcionados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTenantConfig()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenantConfig$Response(params: UpdateTenantConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantConfig>> {
    return updateTenantConfig(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un TenantConfig por ID.
   *
   * Actualiza un TenantConfig  existente usando su ID y los datos proporcionados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTenantConfig$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTenantConfig(params: UpdateTenantConfig$Params, context?: HttpContext): Observable<TenantConfig> {
    return this.updateTenantConfig$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantConfig>): TenantConfig => r.body)
    );
  }

  /** Path part for operation `deleteTenantConfig()` */
  static readonly DeleteTenantConfigPath = '/tenantConfigs/{id}';

  /**
   * TenantConfig a eliminar por ID.
   *
   * Elimina un TenantConfig existente usando su ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTenantConfig()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenantConfig$Response(params: DeleteTenantConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTenantConfig(this.http, this.rootUrl, params, context);
  }

  /**
   * TenantConfig a eliminar por ID.
   *
   * Elimina un TenantConfig existente usando su ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTenantConfig$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTenantConfig(params: DeleteTenantConfig$Params, context?: HttpContext): Observable<void> {
    return this.deleteTenantConfig$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedTenantConfigs()` */
  static readonly GetPaginatedTenantConfigsPath = '/tenantConfigs';

  /**
   * Obtiene una lista paginada de TenantConfig.
   *
   * Devuelve una lista paginada de TenantConfig
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedTenantConfigs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenantConfigs$Response(params?: GetPaginatedTenantConfigs$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoTenantConfig>> {
    return getPaginatedTenantConfigs(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene una lista paginada de TenantConfig.
   *
   * Devuelve una lista paginada de TenantConfig
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedTenantConfigs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedTenantConfigs(params?: GetPaginatedTenantConfigs$Params, context?: HttpContext): Observable<PageResponseDtoTenantConfig> {
    return this.getPaginatedTenantConfigs$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoTenantConfig>): PageResponseDtoTenantConfig => r.body)
    );
  }

  /** Path part for operation `createTenantConfig()` */
  static readonly CreateTenantConfigPath = '/tenantConfigs';

  /**
   * Crear un TenantConfig.
   *
   * Crea un nuevo TenantConfig usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTenantConfig()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenantConfig$Response(params: CreateTenantConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantConfig>> {
    return createTenantConfig(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un TenantConfig.
   *
   * Crea un nuevo TenantConfig usando los datos proporcionados en el cuerpo de la solicitud.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTenantConfig$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTenantConfig(params: CreateTenantConfig$Params, context?: HttpContext): Observable<TenantConfig> {
    return this.createTenantConfig$Response(params, context).pipe(
      map((r: StrictHttpResponse<TenantConfig>): TenantConfig => r.body)
    );
  }

  /** Path part for operation `getAllTenantConfigs()` */
  static readonly GetAllTenantConfigsPath = '/tenantConfigs/all';

  /**
   * Obtiene todos los TenantConfig.
   *
   * Devuelve la lista completa de TenantConfig
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTenantConfigs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenantConfigs$Response(params?: GetAllTenantConfigs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TenantConfig>>> {
    return getAllTenantConfigs(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtiene todos los TenantConfig.
   *
   * Devuelve la lista completa de TenantConfig
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTenantConfigs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTenantConfigs(params?: GetAllTenantConfigs$Params, context?: HttpContext): Observable<Array<TenantConfig>> {
    return this.getAllTenantConfigs$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TenantConfig>>): Array<TenantConfig> => r.body)
    );
  }

}
