/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getTheme } from '../fn/theme-controller/get-theme';
import { GetTheme$Params } from '../fn/theme-controller/get-theme';
import { getThemeByResolvedTenant } from '../fn/theme-controller/get-theme-by-resolved-tenant';
import { GetThemeByResolvedTenant$Params } from '../fn/theme-controller/get-theme-by-resolved-tenant';
import { ThemeDto } from '../models/theme-dto';
import { updateTheme } from '../fn/theme-controller/update-theme';
import { UpdateTheme$Params } from '../fn/theme-controller/update-theme';
import { uploadLogo } from '../fn/theme-controller/upload-logo';
import { UploadLogo$Params } from '../fn/theme-controller/upload-logo';

@Injectable({ providedIn: 'root' })
export class ThemeControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTheme()` */
  static readonly GetThemePath = '/tenants/{tenantCode}/theme';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTheme()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTheme$Response(params: GetTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return getTheme(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTheme$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTheme(params: GetTheme$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.getTheme$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `updateTheme()` */
  static readonly UpdateThemePath = '/tenants/{tenantCode}/theme';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTheme()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTheme$Response(params: UpdateTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return updateTheme(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTheme$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTheme(params: UpdateTheme$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.updateTheme$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `uploadLogo()` */
  static readonly UploadLogoPath = '/tenants/{tenantCode}/theme/logo';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadLogo()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadLogo$Response(params: UploadLogo$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return uploadLogo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadLogo$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadLogo(params: UploadLogo$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.uploadLogo$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

  /** Path part for operation `getThemeByResolvedTenant()` */
  static readonly GetThemeByResolvedTenantPath = '/tenants/config';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getThemeByResolvedTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  getThemeByResolvedTenant$Response(params: GetThemeByResolvedTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
    return getThemeByResolvedTenant(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getThemeByResolvedTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getThemeByResolvedTenant(params: GetThemeByResolvedTenant$Params, context?: HttpContext): Observable<ThemeDto> {
    return this.getThemeByResolvedTenant$Response(params, context).pipe(
      map((r: StrictHttpResponse<ThemeDto>): ThemeDto => r.body)
    );
  }

}
