/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { acceptInvitation } from '../fn/user-invitations/accept-invitation';
import { AcceptInvitation$Params } from '../fn/user-invitations/accept-invitation';
import { createInvitation } from '../fn/user-invitations/create-invitation';
import { CreateInvitation$Params } from '../fn/user-invitations/create-invitation';
import { getInvitations } from '../fn/user-invitations/get-invitations';
import { GetInvitations$Params } from '../fn/user-invitations/get-invitations';
import { InvitationResponse } from '../models/invitation-response';
import { PageResponseDtoInvitationResponse } from '../models/page-response-dto-invitation-response';
import { resendInvitation } from '../fn/user-invitations/resend-invitation';
import { ResendInvitation$Params } from '../fn/user-invitations/resend-invitation';
import { validateToken1 } from '../fn/user-invitations/validate-token-1';
import { ValidateToken1$Params } from '../fn/user-invitations/validate-token-1';


/**
 * REST API for the two-step user onboarding flow: Admin sends invitation → User completes self-registration.
 */
@Injectable({ providedIn: 'root' })
export class UserInvitationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getInvitations()` */
  static readonly GetInvitationsPath = '/auth/invitations';

  /**
   * Get paginated invitations [TENANT_ADMIN].
   *
   * Retrieves a paginated list of all invitations emitted by the specified tenant. Useful for rendering the invitations administrative dashboard.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInvitations()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvitations$Response(params: GetInvitations$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoInvitationResponse>> {
    return getInvitations(this.http, this.rootUrl, params, context);
  }

  /**
   * Get paginated invitations [TENANT_ADMIN].
   *
   * Retrieves a paginated list of all invitations emitted by the specified tenant. Useful for rendering the invitations administrative dashboard.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInvitations$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInvitations(params: GetInvitations$Params, context?: HttpContext): Observable<PageResponseDtoInvitationResponse> {
    return this.getInvitations$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoInvitationResponse>): PageResponseDtoInvitationResponse => r.body)
    );
  }

  /** Path part for operation `createInvitation()` */
  static readonly CreateInvitationPath = '/auth/invitations';

  /**
   * Send a user invitation [TENANT_ADMIN].
   *
   * Creates a pending Invitation and sends an activation email to the specified address. Requires TENANT_ADMIN role.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createInvitation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvitation$Response(params: CreateInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationResponse>> {
    return createInvitation(this.http, this.rootUrl, params, context);
  }

  /**
   * Send a user invitation [TENANT_ADMIN].
   *
   * Creates a pending Invitation and sends an activation email to the specified address. Requires TENANT_ADMIN role.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createInvitation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createInvitation(params: CreateInvitation$Params, context?: HttpContext): Observable<InvitationResponse> {
    return this.createInvitation$Response(params, context).pipe(
      map((r: StrictHttpResponse<InvitationResponse>): InvitationResponse => r.body)
    );
  }

  /** Path part for operation `resendInvitation()` */
  static readonly ResendInvitationPath = '/auth/invitations/{id}/resend';

  /**
   * Resend invitation email [TENANT_ADMIN].
   *
   * Generates a new secure token, pushes back the expiration date by 48 hours, and dispatches a fresh email to the original recipient. Applicable for PENDING or EXPIRED invitations; fails if ACCEPTED.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resendInvitation()` instead.
   *
   * This method doesn't expect any request body.
   */
  resendInvitation$Response(params: ResendInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationResponse>> {
    return resendInvitation(this.http, this.rootUrl, params, context);
  }

  /**
   * Resend invitation email [TENANT_ADMIN].
   *
   * Generates a new secure token, pushes back the expiration date by 48 hours, and dispatches a fresh email to the original recipient. Applicable for PENDING or EXPIRED invitations; fails if ACCEPTED.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resendInvitation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resendInvitation(params: ResendInvitation$Params, context?: HttpContext): Observable<InvitationResponse> {
    return this.resendInvitation$Response(params, context).pipe(
      map((r: StrictHttpResponse<InvitationResponse>): InvitationResponse => r.body)
    );
  }

  /** Path part for operation `acceptInvitation()` */
  static readonly AcceptInvitationPath = '/auth/invitations/accept';

  /**
   * Accept invitation and complete self-registration [PUBLIC].
   *
   * The invited person submits their personal details and credentials. The system creates the User + Person accounts and activates them immediately (auto-activation — no additional Admin approval required).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `acceptInvitation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptInvitation$Response(params: AcceptInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return acceptInvitation(this.http, this.rootUrl, params, context);
  }

  /**
   * Accept invitation and complete self-registration [PUBLIC].
   *
   * The invited person submits their personal details and credentials. The system creates the User + Person accounts and activates them immediately (auto-activation — no additional Admin approval required).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `acceptInvitation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptInvitation(params: AcceptInvitation$Params, context?: HttpContext): Observable<void> {
    return this.acceptInvitation$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `validateToken1()` */
  static readonly ValidateToken1Path = '/auth/invitations/validate';

  /**
   * Validate an invitation token [PUBLIC].
   *
   * Verifies that the given token corresponds to a PENDING, non-expired Invitation. Called by the frontend before rendering the onboarding form.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `validateToken1()` instead.
   *
   * This method doesn't expect any request body.
   */
  validateToken1$Response(params: ValidateToken1$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationResponse>> {
    return validateToken1(this.http, this.rootUrl, params, context);
  }

  /**
   * Validate an invitation token [PUBLIC].
   *
   * Verifies that the given token corresponds to a PENDING, non-expired Invitation. Called by the frontend before rendering the onboarding form.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `validateToken1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  validateToken1(params: ValidateToken1$Params, context?: HttpContext): Observable<InvitationResponse> {
    return this.validateToken1$Response(params, context).pipe(
      map((r: StrictHttpResponse<InvitationResponse>): InvitationResponse => r.body)
    );
  }

}
