/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/vaccine/create';
import { Create$Params } from '../fn/vaccine/create';
import { getAll } from '../fn/vaccine/get-all';
import { GetAll$Params } from '../fn/vaccine/get-all';
import { getById4 } from '../fn/vaccine/get-by-id-4';
import { GetById4$Params } from '../fn/vaccine/get-by-id-4';
import { Vaccine } from '../models/vaccine';


/**
 * MDM para catálogo de vacunas
 */
@Injectable({ providedIn: 'root' })
export class VaccineService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/mdm/vaccine';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<Vaccine>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<Vaccine> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<Vaccine>): Vaccine => r.body)
    );
  }

  /** Path part for operation `getById4()` */
  static readonly GetById4Path = '/mdm/vaccine/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById4()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById4$Response(params: GetById4$Params, context?: HttpContext): Observable<StrictHttpResponse<Vaccine>> {
    return getById4(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById4$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById4(params: GetById4$Params, context?: HttpContext): Observable<Vaccine> {
    return this.getById4$Response(params, context).pipe(
      map((r: StrictHttpResponse<Vaccine>): Vaccine => r.body)
    );
  }

  /** Path part for operation `getAll()` */
  static readonly GetAllPath = '/mdm/vaccine/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll$Response(params?: GetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Vaccine>>> {
    return getAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll(params?: GetAll$Params, context?: HttpContext): Observable<Array<Vaccine>> {
    return this.getAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Vaccine>>): Array<Vaccine> => r.body)
    );
  }

}
