/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Vaccine } from '../../models/vaccine';

export interface GetById4$Params {
  id: number;
}

export function getById4(http: HttpClient, rootUrl: string, params: GetById4$Params, context?: HttpContext): Observable<StrictHttpResponse<Vaccine>> {
  const rb = new RequestBuilder(rootUrl, getById4.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Vaccine>;
    })
  );
}

getById4.PATH = '/mdm/vaccine/{id}';
