/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Departamento } from '../../models/departamento';

export interface CreateDepartamento$Params {
      body: Departamento
}

export function createDepartamento(http: HttpClient, rootUrl: string, params: CreateDepartamento$Params, context?: HttpContext): Observable<StrictHttpResponse<Departamento>> {
  const rb = new RequestBuilder(rootUrl, createDepartamento.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Departamento>;
    })
  );
}

createDepartamento.PATH = '/departamentos';
