/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDtoInvitationResponse } from '../../models/page-response-dto-invitation-response';

export interface GetInvitations$Params {

/**
 * The target Hospital tenant code.
 */
  tenantCode: string;

/**
 * Optional filter by invitation status.
 */
  status?: string;

/**
 * Optional filter by role name.
 */
  role?: string;

/**
 * Zero-based page index.
 */
  pageIndex?: number;

/**
 * Size of the records per page.
 */
  pageSize?: number;
}

export function getInvitations(http: HttpClient, rootUrl: string, params: GetInvitations$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoInvitationResponse>> {
  const rb = new RequestBuilder(rootUrl, getInvitations.PATH, 'get');
  if (params) {
    rb.query('tenantCode', params.tenantCode, {});
    rb.query('status', params.status, {});
    rb.query('role', params.role, {});
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoInvitationResponse>;
    })
  );
}

getInvitations.PATH = '/auth/invitations';
