/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvitationResponse } from '../../models/invitation-response';

export interface ResendInvitation$Params {

/**
 * The database ID of the target UserInvitation to resend.
 */
  id: number;
}

export function resendInvitation(http: HttpClient, rootUrl: string, params: ResendInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationResponse>> {
  const rb = new RequestBuilder(rootUrl, resendInvitation.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationResponse>;
    })
  );
}

resendInvitation.PATH = '/auth/invitations/{id}/resend';
