/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Avatar } from '../../models/avatar';

export interface UpdateAvatar$Params {
  tenantCode: string;
      body?: {
'file': Blob;
}
}

export function updateAvatar(http: HttpClient, rootUrl: string, params: UpdateAvatar$Params, context?: HttpContext): Observable<StrictHttpResponse<Avatar>> {
  const rb = new RequestBuilder(rootUrl, updateAvatar.PATH, 'put');
  if (params) {
    rb.query('tenantCode', params.tenantCode, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Avatar>;
    })
  );
}

updateAvatar.PATH = '/avatars/upload';
