/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDtoCountry } from '../../models/page-response-dto-country';

export interface GetPaginatedCountries$Params {

/**
 * Índice de la página a recuperar.
 */
  pageIndex?: number;

/**
 * Tamaño de la página.
 */
  pageSize?: number;
}

export function getPaginatedCountries(http: HttpClient, rootUrl: string, params?: GetPaginatedCountries$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoCountry>> {
  const rb = new RequestBuilder(rootUrl, getPaginatedCountries.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoCountry>;
    })
  );
}

getPaginatedCountries.PATH = '/countries';
