/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThemeDto } from '../../models/theme-dto';

export interface GetThemeByResolvedTenant$Params {
  'X-Tenant-ID': string;
}

export function getThemeByResolvedTenant(http: HttpClient, rootUrl: string, params: GetThemeByResolvedTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
  const rb = new RequestBuilder(rootUrl, getThemeByResolvedTenant.PATH, 'get');
  if (params) {
    rb.header('X-Tenant-ID', params['X-Tenant-ID'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeDto>;
    })
  );
}

getThemeByResolvedTenant.PATH = '/tenants/config';
