/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantThemeUpdateRequest } from '../../models/tenant-theme-update-request';
import { ThemeDto } from '../../models/theme-dto';

export interface UpdateTheme$Params {
  tenantCode: string;
      body: TenantThemeUpdateRequest
}

export function updateTheme(http: HttpClient, rootUrl: string, params: UpdateTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
  const rb = new RequestBuilder(rootUrl, updateTheme.PATH, 'put');
  if (params) {
    rb.path('tenantCode', params.tenantCode, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeDto>;
    })
  );
}

updateTheme.PATH = '/tenants/{tenantCode}/theme';
