/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThemeDto } from '../../models/theme-dto';

export interface UploadLogo$Params {
  tenantCode: string;
      body?: {
'file': Blob;
}
}

export function uploadLogo(http: HttpClient, rootUrl: string, params: UploadLogo$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDto>> {
  const rb = new RequestBuilder(rootUrl, uploadLogo.PATH, 'post');
  if (params) {
    rb.path('tenantCode', params.tenantCode, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeDto>;
    })
  );
}

uploadLogo.PATH = '/tenants/{tenantCode}/theme/logo';
