/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseDtoBloodType } from '../../models/page-response-dto-blood-type';

export interface GetPaginated3$Params {
  pageIndex?: number;
  pageSize?: number;
}

export function getPaginated3(http: HttpClient, rootUrl: string, params?: GetPaginated3$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoBloodType>> {
  const rb = new RequestBuilder(rootUrl, getPaginated3.PATH, 'get');
  if (params) {
    rb.query('pageIndex', params.pageIndex, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseDtoBloodType>;
    })
  );
}

getPaginated3.PATH = '/mdm/blood-type';
