/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BloodType } from '../../models/blood-type';

export interface GetAll5$Params {
}

export function getAll5(http: HttpClient, rootUrl: string, params?: GetAll5$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BloodType>>> {
  const rb = new RequestBuilder(rootUrl, getAll5.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BloodType>>;
    })
  );
}

getAll5.PATH = '/mdm/blood-type/all';
